# Generated by Django 5.2.3 on 2025-07-05 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizedPain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_part', models.CharField(max_length=100, verbose_name='Parte del Cuerpo')),
                ('pain_level', models.CharField(choices=[('LOW', 'Leve'), ('MODERATE', 'Moderado'), ('HIGH', 'Alto')], max_length=10, verbose_name='Nivel de Dolor')),
                ('periodicity', models.CharField(choices=[('CONSTANT', 'Constante'), ('OCCASIONAL', 'Ocasional'), ('SPECIFIC', 'En momentos específicos')], max_length=15, verbose_name='Periodicidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Dolor Localizado',
                'verbose_name_plural': 'Dolores Localizados',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosha', models.CharField(choices=[('VATA', 'Vata'), ('PITTA', 'Pitta'), ('KAPHA', 'Kapha'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10)),
                ('element', models.CharField(blank=True, choices=[('EARTH', 'Tierra'), ('WATER', 'Agua'), ('FIRE', 'Fuego'), ('AIR', 'Aire'), ('ETHER', 'Éter')], max_length=10)),
                ('diet_type', models.CharField(blank=True, choices=[('OMNIVORE', 'Omnívora'), ('VEGETARIAN', 'Vegetariana'), ('VEGAN', 'Vegana'), ('OTHER', 'Otra')], max_length=15, verbose_name='Tipo de Dieta')),
                ('sleep_quality', models.CharField(blank=True, choices=[('GOOD', 'Buena'), ('REGULAR', 'Regular'), ('POOR', 'Mala')], max_length=10, verbose_name='Calidad de Sueño')),
                ('activity_level', models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentaria'), ('LIGHT', 'Ligera'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta (Atleta)')], max_length=15, verbose_name='Nivel de Actividad')),
                ('accidents_notes', models.TextField(blank=True, verbose_name='Notas sobre Accidentes')),
                ('general_notes', models.TextField(blank=True, verbose_name='Notas Generales del Terapeuta')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
