# Generated by Django 5.2.3 on 2025-07-22 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdoshaanswer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosha_answers', to='profiles.clinicalprofile'),
        ),
        migrations.AddField(
            model_name='clientdoshaanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doshaoption'),
        ),
        migrations.AddField(
            model_name='doshaoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='profiles.doshaquestion'),
        ),
        migrations.AddField(
            model_name='clientdoshaanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doshaquestion'),
        ),
        migrations.AddField(
            model_name='localizedpain',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pains', to='profiles.clinicalprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='doshaoption',
            unique_together={('question', 'associated_dosha')},
        ),
        migrations.AlterUniqueTogether(
            name='clientdoshaanswer',
            unique_together={('profile', 'question')},
        ),
    ]
