# Generated by Django 5.2.3 on 2025-07-09 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ClinicalProfile',
        ),
        migrations.AlterModelOptions(
            name='clinicalprofile',
            options={'verbose_name': 'Perfil Clínico', 'verbose_name_plural': 'Perfiles Clínicos'},
        ),
    ]
