# Generated by Django 5.2.3 on 2025-11-16 03:59

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalprofile',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Alergias conocidas'),
        ),
        migrations.AddField(
            model_name='clinicalprofile',
            name='contraindications',
            field=models.TextField(blank=True, verbose_name='Contraindicaciones'),
        ),
        migrations.AddField(
            model_name='clinicalprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, verbose_name='Condiciones médicas o diagnósticos relevantes'),
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_text', models.TextField(verbose_name='Texto legal presentado')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='profiles.clinicalprofile')),
            ],
            options={
                'verbose_name': 'Consentimiento Clínico',
                'verbose_name_plural': 'Consentimientos Clínicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClinicalProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('dosha', models.CharField(choices=[('VATA', 'Vata'), ('PITTA', 'Pitta'), ('KAPHA', 'Kapha'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10, verbose_name='Dosha Dominante')),
                ('element', models.CharField(blank=True, choices=[('EARTH', 'Tierra'), ('WATER', 'Agua'), ('FIRE', 'Fuego'), ('AIR', 'Aire'), ('ETHER', 'Éter')], max_length=10, verbose_name='Elemento Dominante')),
                ('diet_type', models.CharField(blank=True, choices=[('OMNIVORE', 'Omnívora'), ('VEGETARIAN', 'Vegetariana'), ('VEGAN', 'Vegana'), ('OTHER', 'Otra')], max_length=15, verbose_name='Tipo de Dieta')),
                ('sleep_quality', models.CharField(blank=True, choices=[('GOOD', 'Buena'), ('REGULAR', 'Regular'), ('POOR', 'Mala')], max_length=10, verbose_name='Calidad de Sueño')),
                ('activity_level', models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentaria'), ('LIGHT', 'Ligera'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta (Atleta)')], max_length=15, verbose_name='Nivel de Actividad')),
                ('accidents_notes', models.TextField(blank=True, verbose_name='Notas sobre Accidentes')),
                ('general_notes', models.TextField(blank=True, verbose_name='Notas Generales del Terapeuta')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Condiciones médicas o diagnósticos relevantes')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('contraindications', models.TextField(blank=True, verbose_name='Contraindicaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Perfil Clínico',
                'verbose_name_plural': 'historical Perfiles Clínicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions', to='profiles.clinicalprofile')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Quiosco',
                'verbose_name_plural': 'Sesiones de Quiosco',
                'ordering': ['-created_at'],
            },
        ),
    ]
