# Generated by Django 5.2.3 on 2025-07-09 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_userprofile_clinicalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoshaQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(unique=True, verbose_name='Texto de la Pregunta')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Categoría (ej. Físico, Mental)')),
            ],
            options={
                'verbose_name': 'Pregunta de Dosha',
                'verbose_name_plural': 'Preguntas de Dosha',
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='dosha',
            field=models.CharField(choices=[('VATA', 'Vata'), ('PITTA', 'Pitta'), ('KAPHA', 'Kapha'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10, verbose_name='Dosha Dominante'),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='element',
            field=models.CharField(blank=True, choices=[('EARTH', 'Tierra'), ('WATER', 'Agua'), ('FIRE', 'Fuego'), ('AIR', 'Aire'), ('ETHER', 'Éter')], max_length=10, verbose_name='Elemento Dominante'),
        ),
        migrations.CreateModel(
            name='DoshaOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, verbose_name='Texto de la Opción')),
                ('associated_dosha', models.CharField(choices=[('VATA', 'Vata'), ('PITTA', 'Pitta'), ('KAPHA', 'Kapha')], max_length=5, verbose_name='Dosha Asociado')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Peso/Puntuación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='profiles.doshaquestion')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta Dosha',
                'verbose_name_plural': 'Opciones de Respuesta Dosha',
                'ordering': ['question', 'created_at'],
                'unique_together': {('question', 'associated_dosha')},
            },
        ),
        migrations.CreateModel(
            name='ClientDoshaAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosha_answers', to='profiles.clinicalprofile')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doshaoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doshaquestion')),
            ],
            options={
                'verbose_name': 'Respuesta de Cliente al Cuestionario',
                'verbose_name_plural': 'Respuestas de Clientes al Cuestionario',
                'unique_together': {('profile', 'question')},
            },
        ),
    ]
