# Generated by Django 5.2.3 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_consenttemplate_consentdocument_template_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosksession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('LOCKED', 'Bloqueada'), ('COMPLETED', 'Completada')], default='ACTIVE', max_length=10),
        ),
    ]
