# Generated by Django 4.2

from django.db import migrations

DOSHA_QUESTIONS_DATA = [
    {
        "category": "Físico",
        "text": "Constitución corporal",
        "options": [
            {"dosha": "VATA", "text": "Delgada, alta o muy baja, huesos prominentes."},
            {"dosha": "PITTA", "text": "Mediana, musculatura moderada."},
            {"dosha": "KAPHA", "text": "Fuerte, robusta, huesos grandes."},
        ],
    },
    {
        "category": "Físico",
        "text": "Peso",
        "options": [
            {"dosha": "VATA", "text": "Ligero, dificultad para ganar peso."},
            {"dosha": "PITTA", "text": "Moderado, puedo ganar o perder peso fácilmente."},
            {"dosha": "KAPHA", "text": "Pesado, gano peso fácilmente y lo pierdo con dificultad."},
        ],
    },
    {
        "category": "Físico",
        "text": "Piel",
        "options": [
            {"dosha": "VATA", "text": "Seca, áspera, fría, tendencia a agrietarse."},
            {"dosha": "PITTA", "text": "Suave, cálida, sensible, con pecas o acné."},
            {"dosha": "KAPHA", "text": "Gruesa, grasa, suave, fresca, pálida."},
        ],
    },
    {
        "category": "Físico",
        "text": "Cabello",
        "options": [
            {"dosha": "VATA", "text": "Seco, quebradizo, escaso, oscuro."},
            {"dosha": "PITTA", "text": "Fino, suave, tendencia a canas prematuras o calvicie, rubio o rojizo."},
            {"dosha": "KAPHA", "text": "Grueso, abundante, graso, ondulado, oscuro o claro."},
        ],
    },
    {
        "category": "Digestión",
        "text": "Apetito",
        "options": [
            {"dosha": "VATA", "text": "Irregular, variable. A veces siento hambre, a veces no."},
            {"dosha": "PITTA", "text": "Fuerte e intenso. Me irrito si no como."},
            {"dosha": "KAPHA", "text": "Constante pero lento. Puedo saltarme comidas fácilmente."},
        ],
    },
    {
        "category": "Digestión",
        "text": "Preferencia de sabor",
        "options": [
            {"dosha": "VATA", "text": "Dulce, agrio, salado."},
            {"dosha": "PITTA", "text": "Dulce, amargo, astringente."},
            {"dosha": "KAPHA", "text": "Picante, amargo, astringente."},
        ],
    },
    {
        "category": "Fisiología",
        "text": "Temperatura corporal",
        "options": [
            {"dosha": "VATA", "text": "Manos y pies fríos, prefiero el calor."},
            {"dosha": "PITTA", "text": "Siempre tengo calor, prefiero ambientes frescos."},
            {"dosha": "KAPHA", "text": "Me adapto bien, pero no me gusta el frío húmedo."},
        ],
    },
    {
        "category": "Fisiología",
        "text": "Sueño",
        "options": [
            {"dosha": "VATA", "text": "Ligero, interrumpido, tendencia al insomnio."},
            {"dosha": "PITTA", "text": "Moderado y profundo, pero corto."},
            {"dosha": "KAPHA", "text": "Profundo y prolongado, dificultad para despertar."},
        ],
    },
    {
        "category": "Mental",
        "text": "Temperamento",
        "options": [
            {"dosha": "VATA", "text": "Entusiasta, creativo, pero ansioso y preocupado."},
            {"dosha": "PITTA", "text": "Inteligente, enfocado, ambicioso, pero irritable y crítico."},
            {"dosha": "KAPHA", "text": "Tranquilo, amoroso, paciente, pero propenso al apego y la pereza."},
        ],
    },
    {
        "category": "Mental",
        "text": "Memoria",
        "options": [
            {"dosha": "VATA", "text": "Aprendo rápido, pero olvido rápido."},
            {"dosha": "PITTA", "text": "Buena memoria, clara y enfocada."},
            {"dosha": "KAPHA", "text": "Aprendo lento, pero recuerdo a largo plazo."},
        ],
    },
    {
        "category": "Mental",
        "text": "Estilo de hablar",
        "options": [
            {"dosha": "VATA", "text": "Rápido, hablo mucho."},
            {"dosha": "PITTA", "text": "Claro, preciso, argumentativo."},
            {"dosha": "KAPHA", "text": "Lento, melódico, hablo poco."},
        ],
    },
]


def populate_dosha_questions(apps, schema_editor):
    DoshaQuestion = apps.get_model('profiles', 'DoshaQuestion')
    DoshaOption = apps.get_model('profiles', 'DoshaOption')

    for q_data in DOSHA_QUESTIONS_DATA:
        question, _ = DoshaQuestion.objects.get_or_create(
            text=q_data['text'],
            defaults={'category': q_data['category']}
        )
        for o_data in q_data['options']:
            DoshaOption.objects.get_or_create(
                question=question,
                associated_dosha=o_data['dosha'],
                defaults={'text': o_data['text']}
            )


def delete_dosha_questions(apps, schema_editor):
    DoshaQuestion = apps.get_model('profiles', 'DoshaQuestion')
    question_texts = [q['text'] for q in DOSHA_QUESTIONS_DATA]
    DoshaQuestion.objects.filter(text__in=question_texts).delete()


class Migration(migrations.Migration):

    dependencies = [
        # --- INICIO DE LA CORRECCIÓN ---
        # Se actualiza el nombre de la migración anterior para que coincida con el archivo real.
        ('profiles', '0003_rename_userprofile_clinicalprofile_and_more'),
        # --- FIN DE LA CORRECCIÓN ---
    ]

    operations = [
        migrations.RunPython(populate_dosha_questions, delete_dosha_questions),
    ]