# Generated by Django 5.2.3 on 2025-07-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_doshaquestion_alter_clinicalprofile_dosha_and_more'),
        ('profiles', '0005_populate_dosha_questions'),
    ]

    operations = [
    ]
