# Generated by Django 5.2.3 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_kiosksession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosksession',
            name='has_pending_changes',
            field=models.BooleanField(default=False),
        ),
    ]
