# Generated by Django 5.2.3 on 2025-11-24 23:54

import django.core.validators
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_kiosksession_has_pending_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalprofile',
            name='accidents_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Notas sobre Accidentes'),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='allergies',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Alergias conocidas'),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='contraindications',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Contraindicaciones'),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='general_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Notas Generales del Terapeuta'),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='medical_conditions',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Condiciones médicas o diagnósticos relevantes'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='accidents_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Notas sobre Accidentes'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='allergies',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Alergias conocidas'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='contraindications',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Contraindicaciones'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='general_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Notas Generales del Terapeuta'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='medical_conditions',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Condiciones médicas o diagnósticos relevantes'),
        ),
        migrations.AlterField(
            model_name='localizedpain',
            name='notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Notas Adicionales'),
        ),
        migrations.AddIndex(
            model_name='clinicalprofile',
            index=models.Index(fields=['user'], name='profiles_cl_user_id_4daac3_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalprofile',
            index=models.Index(fields=['dosha', 'element'], name='profiles_cl_dosha_43c4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='consentdocument',
            index=models.Index(fields=['profile', 'is_signed'], name='profiles_co_profile_243b91_idx'),
        ),
        migrations.AddIndex(
            model_name='consentdocument',
            index=models.Index(fields=['template_version', 'created_at'], name='profiles_co_templat_8bd042_idx'),
        ),
        migrations.AddIndex(
            model_name='kiosksession',
            index=models.Index(fields=['token'], name='profiles_ki_token_3f200e_idx'),
        ),
        migrations.AddIndex(
            model_name='kiosksession',
            index=models.Index(fields=['status', 'expires_at'], name='profiles_ki_status_a52d13_idx'),
        ),
        migrations.AddIndex(
            model_name='kiosksession',
            index=models.Index(fields=['profile', 'created_at'], name='profiles_ki_profile_259c66_idx'),
        ),
        migrations.AddIndex(
            model_name='kiosksession',
            index=models.Index(fields=['staff_member', 'created_at'], name='profiles_ki_staff_m_fdd64f_idx'),
        ),
    ]
