# Generated by Django 5.2.3 on 2025-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_adjust_dosha_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdocument',
            name='signature_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalclinicalprofile',
            name='dosha',
            field=models.CharField(choices=[('VATA', 'Vata'), ('PITTA', 'Pitta'), ('KAPHA', 'Kapha'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=7, verbose_name='Dosha Dominante'),
        ),
        migrations.AlterField(
            model_name='localizedpain',
            name='body_part',
            field=models.CharField(choices=[('HEAD', 'Cabeza'), ('NECK', 'Cuello'), ('SHOULDERS', 'Hombros'), ('UPPER_BACK', 'Espalda Alta'), ('LOWER_BACK', 'Espalda Baja'), ('CHEST', 'Pecho'), ('ABDOMEN', 'Abdomen'), ('HIPS', 'Caderas'), ('ARMS', 'Brazos'), ('HANDS', 'Manos'), ('LEGS', 'Piernas'), ('KNEES', 'Rodillas'), ('FEET', 'Pies'), ('OTHER', 'Otro')], max_length=100, verbose_name='Parte del Cuerpo'),
        ),
    ]
