# Generated by Django 5.2.3 on 2025-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_consentdocument_signature_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doshaquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='doshaquestion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
