# Generated by Django 5.2.3 on 2025-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas (Staff/Admin)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='internal_photo_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='URL de Foto Interna (Staff/Admin)'),
        ),
    ]
