# Generated by Django 5.2.3 on 2025-11-16 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('attempt_type', models.CharField(choices=[('REQUEST', 'Solicitud'), ('VERIFY', 'Verificación')], max_length=8)),
                ('is_successful', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Intento OTP',
                'verbose_name_plural': 'Intentos OTP',
                'ordering': ['-created_at'],
            },
        ),
    ]
