# Generated by Django 5.2.3 on 2025-11-16 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Teléfono bloqueado (CNG)',
                'verbose_name_plural': 'Teléfonos bloqueados (CNG)',
            },
        ),
    ]
