# Generated by Django 5.2.3 on 2025-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blockedphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vip_active_since',
            field=models.DateField(blank=True, help_text='Fecha desde la cual el usuario mantiene la membresía VIP de forma ininterrumpida.', null=True, verbose_name='Inicio de actividad VIP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vip_auto_renew',
            field=models.BooleanField(default=True, help_text='Indica si la suscripción VIP debe intentarse renovar automáticamente.', verbose_name='Renovación automática VIP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vip_failed_payments',
            field=models.PositiveIntegerField(default=0, verbose_name='Reintentos fallidos VIP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vip_payment_token',
            field=models.CharField(blank=True, help_text='Token seguro para cobrar renovaciones automáticas.', max_length=255, null=True, verbose_name='Token de pago recurrente'),
        ),
    ]
