# Generated by Django 5.2.3 on 2025-11-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_vip_active_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancellation_streak',
            field=models.JSONField(blank=True, default=list, help_text='Almacena eventos recientes para aplicar penalizaciones (3 strikes).', verbose_name='Historial de cancelaciones/reagendamientos'),
        ),
    ]
