# Generated by Django 5.2.3 on 2025-11-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_indexes_and_phone_validation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_email_c80f75_idx',
            old_name='users_custo_email_e8f2ee_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_role_e4c2f2_idx',
            old_name='users_custo_role_is__2b457f_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_is_pers_cf511b_idx',
            old_name='users_custo_is_pers_07be15_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_vip_exp_386ecf_idx',
            old_name='users_custo_vip_exp_99392d_idx',
        ),
        migrations.RenameIndex(
            model_name='otpattempt',
            new_name='users_otpat_phone_n_300052_idx',
            old_name='users_otpat_phone_n_827658_idx',
        ),
        migrations.RenameIndex(
            model_name='otpattempt',
            new_name='users_otpat_attempt_8a0074_idx',
            old_name='users_otpat_attempt_bb01aa_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='users_users_user_id_3887fe_idx',
            old_name='users_users_user_is__94c994_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='users_users_last_ac_62f4a2_idx',
            old_name='users_users_last_ac_2824a4_idx',
        ),
    ]
