# Generated by Django 5.2.3 on 2025-11-28 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_email_verified_customuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cancellation_streak',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Usar modelo CancellationStreak. Almacena eventos recientes para aplicar penalizaciones (3 strikes).', verbose_name='Historial de cancelaciones/reagendamientos (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vip_payment_token',
            field=models.CharField(blank=True, help_text='Token seguro para cobrar renovaciones automáticas.', max_length=512, null=True, verbose_name='Token de pago recurrente (Encriptado)'),
        ),
        migrations.CreateModel(
            name='CancellationStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha de Cancelación',
                'verbose_name_plural': 'Rachas de Cancelación',
                'ordering': ['-created_at'],
            },
        ),
    ]
