# Generated by Django 5.2.3 on 2025-11-29 02:41

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_cancellation_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vip_payment_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Token seguro para cobrar renovaciones automáticas. Encriptado con Fernet.', null=True, verbose_name='Token de pago recurrente (Encriptado)'),
        ),
    ]
