# Generated by Django 5.2.3 on 2025-12-01

from django.conf import settings
from django.db import migrations
from cryptography.fernet import Fernet, InvalidToken
import fernet_fields.fields


def encrypt_existing_totp(apps, schema_editor):
    """
    Re-cifra los secretos TOTP existentes para evitar que queden en texto plano.
    Si ya estaban cifrados, los deja intactos.
    """
    CustomUser = apps.get_model("users", "CustomUser")
    key = getattr(settings, "FERNET_KEYS", [None])[0]
    if not key:
        return

    fernet = Fernet(key)
    for user in CustomUser.objects.exclude(totp_secret__isnull=True).exclude(totp_secret=""):
        secret = user.totp_secret
        try:
            # Si ya está cifrado y se puede descifrar, continuar.
            fernet.decrypt(secret.encode())
            continue
        except (InvalidToken, ValueError):
            pass

        try:
            user.totp_secret = fernet.encrypt(secret.encode()).decode()
            user.save(update_fields=["totp_secret"])
        except Exception:
            # Falla silenciosa para no romper migración si algún registro está corrupto.
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_encrypt_vip_payment_token"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_totp, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customuser",
            name="totp_secret",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Guardado cifrado con Fernet. No se almacena en texto plano.",
                null=True,
                verbose_name="Secreto TOTP (2FA App, Encriptado)",
            ),
        ),
    ]
