from decimal import Decimal

SERVICE_CATALOG = [
    {
        "key": "integrales",
        "name": "Integrales",
        "description": "Terapias completas que trabajan todo el cuerpo para restaurar el equilibrio físico y energético.",
        "is_low_supervision": False,
        "services": [
            {
                "name": "Terapéutico Completo",
                "description": "Masaje terapéutico de cuerpo completo que combina técnicas de tejido profundo y relajación para liberar tensiones musculares y mejorar la circulación.",
                "duration": 90,
                "price": "150000.00",
                "vip_price": "135000.00",
                "what_is_included": "• Masaje de espalda, cuello y hombros con técnicas de tejido profundo\n• Trabajo en piernas y pies con drenaje\n• Masaje de brazos y manos\n• Aceites esenciales de aromaterapia personalizados\n• Música relajante ambiental",
                "benefits": "• Libera tensiones musculares acumuladas\n• Mejora la circulación sanguínea y linfática\n• Reduce el estrés y la ansiedad\n• Aumenta la flexibilidad muscular\n• Promueve el sueño reparador",
                "contraindications": "• Fiebre o infecciones activas\n• Fracturas recientes o lesiones abiertas\n• Trombosis venosa profunda\n• Primer trimestre de embarazo\n• Quemaduras solares recientes",
            },
            {
                "name": "Terapéutico Focalizado",
                "description": "Tratamiento específico en zonas de mayor tensión como espalda, cuello y hombros, ideal para aliviar contracturas puntuales.",
                "duration": 50,
                "price": "130000.00",
                "vip_price": "117000.00",
                "what_is_included": "• Evaluación inicial de puntos de tensión\n• Masaje profundo en zona focalizada (espalda, cuello u hombros)\n• Técnicas de liberación miofascial\n• Aplicación de calor localizado si es necesario\n• Aceite terapéutico antiinflamatorio",
                "benefits": "• Alivio inmediato de contracturas\n• Reduce dolores de cabeza tensionales\n• Mejora la postura\n• Disminuye el dolor cervical\n• Aumenta el rango de movimiento",
                "contraindications": "• Hernias discales agudas\n• Inflamación severa en la zona\n• Lesiones musculares recientes (menos de 48h)\n• Osteoporosis avanzada\n• Anticoagulantes sin supervisión médica",
            },
            {
                "name": "Terapéutico Mixto",
                "description": "Equilibrio perfecto entre terapia profunda en zonas críticas y masaje relajante en el resto del cuerpo.",
                "duration": 75,
                "price": "145000.00",
                "vip_price": "130000.00",
                "what_is_included": "• Trabajo profundo en áreas de mayor tensión\n• Masaje relajante en zonas complementarias\n• Estiramientos pasivos suaves\n• Aceites esenciales premium\n• Técnica de piedras calientes en puntos clave",
                "benefits": "• Combina los beneficios terapéuticos y relajantes\n• Equilibrio entre alivio muscular y relajación mental\n• Mejora del estado de ánimo\n• Reducción del cortisol\n• Sensación de renovación completa",
                "contraindications": "• Condiciones cardíacas severas\n• Cáncer activo sin autorización médica\n• Infecciones en la piel\n• Estado de embriaguez\n• Fiebre alta",
            },
        ],
    },
    {
        "key": "detox",
        "name": "Detox",
        "description": "Protocolos de desintoxicación que estimulan el sistema linfático y eliminan toxinas del organismo.",
        "is_low_supervision": False,
        "services": [
            {
                "name": "Drenaje Linfático",
                "description": "Técnica suave y rítmica que activa el sistema linfático para reducir retención de líquidos, mejorar la circulación y fortalecer el sistema inmune.",
                "duration": 60,
                "price": "140000.00",
                "vip_price": "126000.00",
                "what_is_included": "• Movimientos suaves y rítmicos siguiendo el sistema linfático\n• Trabajo en ganglios principales (cuello, axilas, inglés)\n• Técnica específica para reducir edemas\n• Aceite neutro hipoalergénico\n• Recomendaciones post-tratamiento",
                "benefits": "• Reduce la retención de líquidos\n• Mejora la circulación linfática\n• Fortalece el sistema inmunológico\n• Acelera la eliminación de toxinas\n• Reduce la celulitis y la piel de naranja",
                "contraindications": "• Infecciones agudas o fiebre\n• Insuficiencia cardíaca descompensada\n• Trombosis o flebitis\n• Hipotiroidismo no tratado\n• Cáncer sin autorización oncológica",
            },
            {
                "name": "Terapia de Equilibrio",
                "description": "Tratamiento holístico que combina drenaje linfático con puntos de acupresión para restaurar el balance energético del cuerpo.",
                "duration": 75,
                "price": "155000.00",
                "vip_price": "139000.00",
                "what_is_included": "• Drenaje linfático suave\n• Estimulación de puntos de acupresión\n• Trabajo en meridianos energéticos\n• Aceites esenciales equilibrantes\n• Momento de meditación guiada",
                "benefits": "• Restaura el equilibrio energético\n• Reduce el estrés emocional\n• Mejora la calidad del sueño\n• Armoniza cuerpo y mente\n• Aumenta la vitalidad general",
                "contraindications": "• Primer trimestre de embarazo\n• Marcapasos cardíaco\n• Epilepsia no controlada\n• Estados de ansiedad severa\n• Heridas abiertas en puntos de presión",
            },
            {
                "name": "Udvartana",
                "description": "Masaje ayurvédico con polvos herbales que exfolia, tonifica y estimula la circulación mientras elimina toxinas acumuladas en la piel.",
                "duration": 90,
                "price": "170000.00",
                "vip_price": "153000.00",
                "what_is_included": "• Exfoliación con polvos herbales ayurvédicos\n• Masaje vigoroso en dirección de los meridianos\n• Aceites herbales calientes\n• Envolvimiento detox (opcional)\n• Ducha para retirar polvos",
                "benefits": "• Exfolia y renueva la piel\n• Reduce la celulitis y grasa localizada\n• Tonifica los tejidos\n• Activa el metabolismo\n• Deja la piel suave y radiante",
                "contraindications": "• Piel muy sensible o con eczema activo\n• Quemaduras solares\n• Heridas abiertas\n• Alergia a hierbas (consultar ingredientes)\n• Embarazo",
            },
        ],
    },
    {
        "key": "spa",
        "name": "Spa",
        "description": "Experiencias sensoriales de relajación profunda y cuidado integral del cuerpo y la mente.",
        "is_low_supervision": True,
        "services": [
            {
                "name": "Experiencia Zen",
                "description": "Ritual de relajación que integra aromaterapia, música terapéutica y técnicas de masaje suaves para alcanzar un estado de calma profunda.",
                "duration": 60,
                "price": "135000.00",
                "vip_price": "121000.00",
                "what_is_included": "• Masaje relajante de cuerpo completo\n• Aromaterapia con aceites esenciales premium\n• Música terapéutica 432Hz\n• Ambiente con iluminación tenue\n• Té herbal de cortesía",
                "benefits": "• Relajación profunda del sistema nervioso\n• Reducción del estrés y ansiedad\n• Mejora el estado de ánimo\n• Promueve la claridad mental\n• Sensación de paz interior",
                "contraindications": "• Alergia a aceites esenciales (informar antes)\n• Claustrofobia severa\n• Condiciones que impidan estar recostado\n• Sensibilidad extrema a olores",
            },
            {
                "name": "Zen Extendido",
                "description": "Versión extendida de la Experiencia Zen con mayor tiempo dedicado a cada zona del cuerpo y técnicas de meditación guiada.",
                "duration": 90,
                "price": "165000.00",
                "vip_price": "148000.00",
                "what_is_included": "• Todo lo incluido en Experiencia Zen\n• 30 minutos adicionales de masaje\n• Meditación guiada al inicio\n• Técnica de respiración consciente\n• Mascarilla facial express",
                "benefits": "• Relajación más profunda y duradera\n• Conexión mente-cuerpo\n• Reset completo del sistema nervioso\n• Mejora la calidad del sueño durante días\n• Renovación de energía vital",
                "contraindications": "• Las mismas que Experiencia Zen\n• Dificultad para permanecer quieto por tiempo prolongado",
            },
            {
                "name": "Toque de Seda",
                "description": "Masaje delicado con aceites nutritivos que hidrata profundamente la piel mientras relaja el cuerpo con movimientos envolventes y sedosos.",
                "duration": 75,
                "price": "145000.00",
                "vip_price": "130000.00",
                "what_is_included": "• Masaje con técnica sueca suave\n• Aceites nutritivos de argán y jojoba\n• Movimientos largos y envolventes\n• Atención especial a zonas secas\n• Hidratación final intensiva",
                "benefits": "• Hidratación profunda de la piel\n• Nutrición de tejidos\n• Relajación muscular suave\n• Piel sedosa y luminosa\n• Mejora la elasticidad cutánea",
                "contraindications": "• Alergia a frutos secos (por aceites)\n• Acné severo en cuerpo\n• Piel con heridas abiertas",
            },
            {
                "name": "Herbal Essence",
                "description": "Tratamiento revitalizante con aceites esenciales herbales de notas masculinas, combinando masaje profundo y aromaterapia energizante.",
                "duration": 75,
                "price": "145000.00",
                "vip_price": "130000.00",
                "what_is_included": "• Masaje con presión media-profunda\n• Aceites de romero, menta y eucalipto\n• Técnicas energizantes\n• Trabajo en puntos de tensión\n• Toalla caliente en espalda",
                "benefits": "• Revitaliza el cuerpo y la mente\n• Alivia la fatiga muscular\n• Despeja las vías respiratorias\n• Aumenta el estado de alerta\n• Ideal después del ejercicio",
                "contraindications": "• Hipertensión no controlada\n• Sensibilidad al eucalipto o menta\n• Asma severa (consultar)\n• Migrañas activas",
            },
            {
                "name": "Cráneo Facial Ensueño",
                "description": "Masaje facial y craneal que libera tensiones acumuladas en rostro, cuero cabelludo y cuello, promoviendo relajación mental profunda.",
                "duration": 45,
                "price": "120000.00",
                "vip_price": "108000.00",
                "what_is_included": "• Masaje craneal con técnica india\n• Trabajo facial con aceites nutritivos\n• Masaje de cuello y hombros\n• Acupresión en puntos de tensión facial\n• Aceite capilar nutritivo",
                "benefits": "• Alivia dolores de cabeza\n• Reduce la tensión mandibular\n• Mejora la circulación facial\n• Promueve el crecimiento capilar\n• Relajación mental profunda",
                "contraindications": "• Sinusitis aguda\n• Migraña en curso\n• Conjuntivitis u otras infecciones oculares\n• Cirugía facial reciente",
            },
            {
                "name": "Cráneo Facial Ocaso",
                "description": "Ritual vespertino que combina técnicas de acupresión facial con masaje craneal para aliviar el estrés del día y preparar el descanso.",
                "duration": 50,
                "price": "130000.00",
                "vip_price": "117000.00",
                "what_is_included": "• Limpieza facial suave\n• Acupresión en puntos de medicina china\n• Masaje craneal relajante\n• Aceites esenciales de lavanda\n• Compresa tibia en ojos",
                "benefits": "• Prepara para el descanso nocturno\n• Alivia la fatiga visual\n• Reduce el bruxismo\n• Mejora la calidad del sueño\n• Suaviza líneas de expresión",
                "contraindications": "• Alergia a lavanda\n• Glaucoma\n• Desprendimiento de retina\n• Botox reciente (menos de 2 semanas)",
            },
            {
                "name": "Cráneo Facial Renacer",
                "description": "Tratamiento revitalizante que estimula puntos energéticos del rostro y cráneo para renovar la vitalidad y luminosidad de la piel.",
                "duration": 60,
                "price": "145000.00",
                "vip_price": "130000.00",
                "what_is_included": "• Exfoliación facial suave\n• Masaje lifting natural\n• Estimulación de puntos energéticos\n• Mascarilla revitalizante\n• Masaje craneal activador",
                "benefits": "• Efecto lifting natural inmediato\n• Luminosidad y frescura facial\n• Activa la circulación\n• Reduce la hinchazón matutina\n• Renueva la energía vital",
                "contraindications": "• Rosacea activa\n• Acné inflamatorio\n• Tratamientos estéticos recientes\n• Piel con heridas o irritación",
            },
            {
                "name": "Pediluvio",
                "description": "Baño terapéutico de pies con sales minerales y aceites esenciales, seguido de masaje reflexológico para activar puntos de bienestar.",
                "duration": 30,
                "price": "80000.00",
                "vip_price": "72000.00",
                "what_is_included": "• Baño de pies con sales minerales\n• Exfoliación de pies\n• Masaje reflexológico\n• Hidratación intensiva\n• Aceites esenciales relajantes",
                "benefits": "• Activa puntos reflejos de todo el cuerpo\n• Mejora la circulación de piernas\n• Reduce pies cansados e hinchados\n• Hidrata piel agrietada\n• Relajación a través de los pies",
                "contraindications": "• Pie diabético sin control\n• Hongos activos en pies\n• Heridas abiertas en pies\n• Varices severas",
            },
            {
                "name": "Limpieza Facial Sencilla",
                "description": "Protocolo básico de limpieza profunda que elimina impurezas, exfolia suavemente y equilibra la piel del rostro.",
                "duration": 45,
                "price": "110000.00",
                "vip_price": "99000.00",
                "what_is_included": "• Doble limpieza facial\n• Exfoliación enzimática suave\n• Extracción de impurezas (si aplica)\n• Mascarilla equilibrante\n• Hidratación según tipo de piel",
                "benefits": "• Piel limpia y luminosa\n• Poros desobstruidos\n• Textura más suave\n• Mejor absorción de productos\n• Rostro fresco y renovado",
                "contraindications": "• Herpes activo\n• Rosácea severa\n• Quemaduras solares\n• Tratamientos de Accutane en curso\n• Peeling químico reciente",
            },
            {
                "name": "Hidra Facial",
                "description": "Tratamiento facial avanzado con tecnología de hidrodermabrasión que limpia, exfolia e hidrata profundamente para una piel radiante.",
                "duration": 60,
                "price": "180000.00",
                "vip_price": "162000.00",
                "what_is_included": "• Limpieza profunda con tecnología\n• Hidrodermabrasión profesional\n• Extracción indolora de impurezas\n• Infusión de serums según necesidad\n• Mascarilla LED (opcional)\n• Protección solar final",
                "benefits": "• Limpieza profunda sin irritación\n• Hidratación inigualable\n• Resultados visibles inmediatos\n• Reduce líneas finas\n• Piel radiante y juvenil",
                "contraindications": "• Embarazo (algunas tecnologías)\n• Marca pasos\n• Rosácea activa\n• Herpes labial\n• Alergias severas a productos faciales",
            },
        ],
    },
]

__all__ = ["SERVICE_CATALOG"]
