DEMO_USERS = [
    {
        "label": "Terapeuta Andrea",
        "phone_number": "+573102000001",
        "email": "andrea.demo@studiozens.test",
        "first_name": "Andrea",
        "last_name": "Calma",
        "role": "STAFF",
        "is_staff": True,
        "is_verified": True,
        "password": "DemoStaff123!",
        "internal_notes": "Trabajadora demo creada por seed_demo_data.",
        "issue_tokens": True,
    },
    {
        "label": "Terapeuta Mateo",
        "phone_number": "+573102000002",
        "email": "mateo.demo@studiozens.test",
        "first_name": "Mateo",
        "last_name": "Balance",
        "role": "STAFF",
        "is_staff": True,
        "is_verified": True,
        "password": "DemoStaff123!",
        "internal_notes": "Trabajador demo creado por seed_demo_data.",
        "issue_tokens": True,
    },
    {
        "label": "Cliente Laura",
        "phone_number": "+573102000101",
        "email": "laura.demo@studiozens.test",
        "first_name": "Laura",
        "last_name": "Serenidad",
        "role": "CLIENT",
        "is_staff": False,
        "is_verified": True,
        "password": "DemoCliente123!",
        "internal_notes": "Cliente demo registrado y autenticado automáticamente.",
        "issue_tokens": True,
    },
    {
        "label": "Cliente David",
        "phone_number": "+573102000102",
        "email": "david.demo@studiozens.test",
        "first_name": "David",
        "last_name": "Vital",
        "role": "CLIENT",
        "is_staff": False,
        "is_verified": True,
        "password": "DemoCliente123!",
        "internal_notes": "Cliente demo registrado y autenticado automáticamente.",
        "issue_tokens": True,
    },
]

__all__ = ["DEMO_USERS"]
