# Generated by Django 5.2.3 on 2025-07-05 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin')], max_length=50, verbose_name='Acción Realizada')),
                ('details', models.TextField(blank=True, verbose_name='Detalles Adicionales')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
