# Generated by Django 5.2.3 on 2025-07-22 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin')], max_length=50, verbose_name='Acción Realizada')),
                ('details', models.TextField(blank=True, verbose_name='Detalles Adicionales')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_supervision_capacity', models.PositiveIntegerField(default=1, help_text='Número máximo de citas de baja supervisión que pueden ocurrir simultáneamente.', verbose_name='Capacidad Máxima para Servicios de Baja Supervisión')),
                ('advance_payment_percentage', models.PositiveIntegerField(default=20, help_text='Porcentaje del costo total de la cita que se debe pagar como anticipo.', verbose_name='Porcentaje de Anticipo Requerido (%)')),
                ('appointment_buffer_time', models.PositiveIntegerField(default=10, help_text='Minutos de búfer que se añadirán después de cada cita para preparación.', verbose_name='Tiempo de Limpieza entre Citas (minutos)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
    ]
