# Generated by Django 5.2.3 on 2025-11-16 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('spa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Admin'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_appointment',
            field=models.ForeignKey(blank=True, help_text='Cita relacionada con la acción (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.appointment'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Objetivo'),
        ),
        migrations.AddIndex(
            model_name='globalsettings',
            index=models.Index(fields=['updated_at'], name='core_global_updated_3682a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['admin_user'], name='core_auditl_admin_u_435283_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_user'], name='core_auditl_target__bd5329_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_appointment'], name='core_auditl_target__82fbca_idx'),
        ),
    ]
