# Generated by Django 5.2.3 on 2025-07-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('spa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Admin'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_appointment',
            field=models.ForeignKey(blank=True, help_text='Link to a specific appointment related to the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.appointment'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Objetivo'),
        ),
    ]
