# Generated by Django 5.2.3 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin'), ('CLINICAL_PROFILE_ANONYMIZED', 'Perfil clínico anonimizado')], max_length=64, verbose_name='Acción Realizada'),
        ),
    ]
