# Generated by Django 5.2.3 on 2025-07-14 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_supervision_capacity', models.PositiveIntegerField(default=1, help_text='Número máximo de citas de baja supervisión que pueden ocurrir simultáneamente.', verbose_name='Capacidad Máxima para Servicios de Baja Supervisión')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
    ]
