# Generated by Django 5.2.3 on 2025-11-16 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='advance_expiration_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Tiempo máximo para pagar el anticipo antes de cancelar automáticamente.', verbose_name='Minutos para cancelar citas sin pago'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='credit_expiration_days',
            field=models.PositiveIntegerField(default=365, help_text='Número de días antes de que un saldo a favor expire.', verbose_name='Días de vigencia para créditos'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='no_show_credit_policy',
            field=models.CharField(choices=[('NONE', 'Sin crédito'), ('PARTIAL', 'Crédito parcial'), ('FULL', 'Crédito total')], default='NONE', help_text='Regla para convertir anticipos en crédito cuando hay No-Show.', max_length=10),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], default='PENDING', max_length=10)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
