# Generated by Django 5.2.3 on 2025-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='advance_payment_percentage',
            field=models.PositiveIntegerField(default=20, help_text='Porcentaje del costo total de la cita que se debe pagar como anticipo.', verbose_name='Porcentaje de Anticipo Requerido (%)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='appointment_buffer_time',
            field=models.PositiveIntegerField(default=10, help_text='Minutos de búfer que se añadirán después de cada cita para preparación.', verbose_name='Tiempo de Limpieza entre Citas (minutos)'),
        ),
    ]
