# Generated by Django 5.2.3 on 2025-11-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globalsettings_advance_expiration_minutes_and_more'),
        ('spa', '0006_webhookevent_voucher_expires_at_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='loyalty_months_required',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de meses continuos como VIP para recibir un beneficio.', verbose_name='Meses continuos para recompensa VIP'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='loyalty_voucher_service',
            field=models.ForeignKey(blank=True, help_text='Servicio que se otorga como voucher al cumplir la lealtad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spa.service', verbose_name='Servicio de recompensa VIP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin'), ('CLINICAL_PROFILE_ANONYMIZED', 'Perfil clínico anonimizado'), ('VOUCHER_REDEEMED', 'Voucher redimido'), ('LOYALTY_REWARD_ISSUED', 'Recompensa de lealtad otorgada'), ('VIP_DOWNGRADED', 'VIP degradado')], max_length=64, verbose_name='Acción Realizada'),
        ),
    ]
