# Generated by Django 5.2.3 on 2025-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_globalsettings_loyalty_months_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Número máximo de días para aceptar devoluciones desde la entrega.', verbose_name='Ventana de devoluciones (días)'),
        ),
    ]
