# Generated by Django 5.2.3 on 2025-11-17 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAGOS', 'Pagos'), ('SUSCRIPCIONES', 'Suscripciones'), ('USUARIOS', 'Usuarios')], default='USUARIOS', max_length=20)),
                ('subtype', models.CharField(choices=[('PAGO_EXITOSO', 'Pago exitoso'), ('PAGO_FALLIDO', 'Pago fallido'), ('USUARIO_CNG', 'Usuario marcado como CNG'), ('USUARIO_RECURRENTE', 'Usuario recurrente'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación Administrativa',
                'verbose_name_plural': 'Notificaciones Administrativas',
                'ordering': ['-created_at'],
            },
        ),
    ]
