# Generated by Django 5.2.3 on 2025-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_adminnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("FLAG_NON_GRATA", "Marcar como Persona No Grata"),
                    ("ADMIN_CANCEL_APPOINTMENT", "Admin cancela cita pagada"),
                    (
                        "APPOINTMENT_CANCELLED_BY_ADMIN",
                        "Appointment Cancelled by Admin",
                    ),
                    ("SYSTEM_CANCEL", "Cancelación automática del sistema"),
                    (
                        "APPOINTMENT_RESCHEDULE_FORCE",
                        "Reagendamiento forzado por staff",
                    ),
                    (
                        "CLINICAL_PROFILE_ANONYMIZED",
                        "Perfil clínico anonimizado",
                    ),
                    ("VOUCHER_REDEEMED", "Voucher redimido"),
                    ("LOYALTY_REWARD_ISSUED", "Recompensa de lealtad otorgada"),
                    ("VIP_DOWNGRADED", "VIP degradado"),
                    (
                        "MARKETPLACE_RETURN",
                        "Devolución marketplace procesada",
                    ),
                ],
                max_length=64,
                verbose_name="Acción Realizada",
            ),
        ),
    ]
