# Generated by Django 5.2.3 on 2025-11-18 09:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action_marketplacereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='developer_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje reservado para el desarrollador. Solo puede mantenerse o incrementarse.', max_digits=5, verbose_name='Comisión del desarrollador (%)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='developer_default_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de mora con el desarrollador'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='developer_in_default',
            field=models.BooleanField(default=False, help_text='Indica si el sistema adeuda pagos al desarrollador.', verbose_name='Desarrollador en mora'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='developer_payout_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000.00'), help_text='Saldo mínimo acumulado antes de intentar una dispersión al desarrollador.', max_digits=12, verbose_name='Umbral de pago al desarrollador'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='Hora en la que termina la ventana de silencio.', null=True, verbose_name='Fin de horas de silencio'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Hora desde la cual se silencian notificaciones no críticas.', null=True, verbose_name='Inicio de horas de silencio'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='timezone_display',
            field=models.CharField(default='America/Bogota', help_text='Zona horaria usada para mostrar fechas al usuario.', max_length=64, verbose_name='Zona horaria de visualización'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='waitlist_enabled',
            field=models.BooleanField(default=False, help_text='Permite activar/desactivar el módulo de lista de espera.', verbose_name='Lista de espera habilitada'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='waitlist_ttl_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo máximo para responder a una oferta de lista de espera.', verbose_name='TTL de lista de espera (minutos)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('ADMIN_ENDPOINT_HIT', 'Invocación de endpoint admin'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin'), ('SYSTEM_CANCEL', 'Cancelación automática del sistema'), ('APPOINTMENT_RESCHEDULE_FORCE', 'Reagendamiento forzado por staff'), ('APPOINTMENT_COMPLETED', 'Cita completada'), ('CLINICAL_PROFILE_ANONYMIZED', 'Perfil clínico anonimizado'), ('VOUCHER_REDEEMED', 'Voucher redimido'), ('LOYALTY_REWARD_ISSUED', 'Recompensa de lealtad otorgada'), ('VIP_DOWNGRADED', 'VIP degradado'), ('MARKETPLACE_RETURN', 'Devolución marketplace procesada'), ('FINANCIAL_ADJUSTMENT_CREATED', 'Ajuste financiero registrado')], max_length=64, verbose_name='Acción Realizada'),
        ),
    ]
