# Generated by Django 5.2.3 on 2025-11-24 13:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_globalsettings_developer_commission_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key'], name='core_idempo_key_145b58_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['status', 'completed_at'], name='core_idempo_status_35db88_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['status', 'locked_at'], name='core_idempo_status_323cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['user', 'created_at'], name='core_idempo_user_id_aa987a_idx'),
        ),
    ]
