# Generated by Django 5.2.3 on 2025-11-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_idempotencykey_request_hash_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='core_idempo_request_9b0aea_idx',
            old_name='core_idempo_request_hash_idx',
        ),
    ]
