# Generated by Django 5.2.3 on 2025-12-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_idempo_request_hash_idx_core_idempo_request_9b0aea_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='advance_payment_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Porcentaje del costo total de la cita que se debe pagar como anticipo.', verbose_name='Porcentaje de Anticipo Requerido (%)'),
        ),
    ]
