# Generated by Django 5.2.3 on 2025-12-14 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_change_advance_payment_to_40_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.TextField(blank=True, help_text='Declaración de la misión de StudioZens', verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='Declaración de la visión de StudioZens', verbose_name='Visión')),
                ('values', models.TextField(blank=True, help_text='Valores corporativos de StudioZens', verbose_name='Valores')),
                ('history', models.TextField(blank=True, help_text='Historia de StudioZens', verbose_name='Historia')),
                ('team_description', models.TextField(blank=True, help_text='Descripción general del equipo de trabajo', verbose_name='Descripción del Equipo')),
                ('hero_image', models.ImageField(blank=True, help_text='Imagen hero de la página Quiénes Somos', null=True, upload_to='about/hero/', verbose_name='Imagen Principal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('business_hours', models.TextField(blank=True, default='Lunes a Sábado: 9:00 AM - 8:00 PM\nDomingos: Cerrado', help_text='Horarios de atención al público', verbose_name='Horarios de Atención')),
            ],
            options={
                'verbose_name': 'Página Quiénes Somos',
                'verbose_name_plural': 'Página Quiénes Somos',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo/Posición')),
                ('bio', models.TextField(blank=True, help_text='Breve descripción del miembro del equipo', verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en que aparece en la página (menor = primero)', verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en la página', verbose_name='Activo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['order', 'name'],
            },
        ),
    ]
