# Generated by Django 5.2.3 on 2025-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aboutpage_galleryimage_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración completa de la página en formato JSON', null=True, verbose_name='Contenido de la Página'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('ADMIN_ENDPOINT_HIT', 'Invocación de endpoint admin'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin'), ('SYSTEM_CANCEL', 'Cancelación automática del sistema'), ('APPOINTMENT_RESCHEDULE_FORCE', 'Reagendamiento forzado por staff'), ('APPOINTMENT_COMPLETED', 'Cita completada'), ('CLINICAL_PROFILE_ANONYMIZED', 'Perfil clínico anonimizado'), ('VOUCHER_REDEEMED', 'Voucher redimido'), ('LOYALTY_REWARD_ISSUED', 'Recompensa de lealtad otorgada'), ('VIP_DOWNGRADED', 'VIP degradado'), ('MARKETPLACE_RETURN', 'Devolución marketplace procesada'), ('FINANCIAL_ADJUSTMENT_CREATED', 'Ajuste financiero registrado'), ('USER_DELETED_PERMANENTLY', 'Usuario eliminado permanentemente')], max_length=64, verbose_name='Acción Realizada'),
        ),
    ]
