# Generated by Django 5.2.3 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aboutpage_content_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('FLAG_NON_GRATA', 'Marcar como Persona No Grata'), ('ADMIN_CANCEL_APPOINTMENT', 'Admin cancela cita pagada'), ('ADMIN_ENDPOINT_HIT', 'Invocación de endpoint admin'), ('APPOINTMENT_CANCELLED_BY_ADMIN', 'Appointment Cancelled by Admin'), ('SYSTEM_CANCEL', 'Cancelación automática del sistema'), ('APPOINTMENT_RESCHEDULE_FORCE', 'Reagendamiento forzado por staff'), ('APPOINTMENT_COMPLETED', 'Cita completada'), ('CLINICAL_PROFILE_ANONYMIZED', 'Perfil clínico anonimizado'), ('VOUCHER_REDEEMED', 'Voucher redimido'), ('VOUCHER_CREATED', 'Voucher creado manualmente'), ('LOYALTY_REWARD_ISSUED', 'Recompensa de lealtad otorgada'), ('VIP_DOWNGRADED', 'VIP degradado'), ('MARKETPLACE_RETURN', 'Devolución marketplace procesada'), ('FINANCIAL_ADJUSTMENT_CREATED', 'Ajuste financiero registrado'), ('USER_DELETED_PERMANENTLY', 'Usuario eliminado permanentemente'), ('APPOINTMENT_CREATED_BY_ADMIN', 'Cita creada por admin para cliente'), ('PAYMENT_RECEIVED_IN_PERSON', 'Pago recibido en persona')], max_length=64, verbose_name='Acción Realizada'),
        ),
    ]
