# Generated by Django 5.2.3 on 2026-01-05 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='vip_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de descuento aplicado a servicios para usuarios VIP.', max_digits=5, verbose_name='Porcentaje de Descuento VIP (%)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='developer_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje reservado para el desarrollador. Mínimo permitido: 5%.', max_digits=5, verbose_name='Comisión del desarrollador (%)'),
        ),
    ]
