# Generated by Django 5.2.3 on 2026-01-05 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_globalsettings_vip_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='vip_cashback_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Porcentaje de reintegro en créditos para usuarios VIP sobre pagos realizados.', max_digits=5, verbose_name='Porcentaje de Cashback VIP (%)'),
        ),
    ]
