# Generated by Django 5.2.3 on 2026-01-05 22:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_globalsettings_vip_cashback_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='vip_loyalty_credit_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Cantidad de créditos otorgados automáticamente al cumplir la lealtad.', max_digits=10, verbose_name='Recompensa de lealtad VIP (Créditos)'),
        ),
    ]
