# Generated by Django 5.2.3 on 2026-01-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_globalsettings_vip_loyalty_credit_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='vip_monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo en COP para una suscripción mensual VIP.', max_digits=12, verbose_name='Precio Mensual VIP'),
        ),
    ]
