# Generated by Django 5.2.3 on 2025-12-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_legal_slug_ad8e2d_idx',
            old_name='legal_legald_slug_versi_b7f135_idx',
        ),
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='legal_legal_doc_typ_a04c5b_idx',
            old_name='legal_legald_doc_typ_c0ce6a_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='legal_userc_documen_fa6bb2_idx',
            old_name='legal_userco_document_6df65c_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='legal_userc_user_id_81403f_idx',
            old_name='legal_userco_user_id_3ae876_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='legal_userc_anonymo_c579c2_idx',
            old_name='legal_userco_anonymo_99b87e_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='legal_userc_context_5a5fb4_idx',
            old_name='legal_userco_context_78b0b1_idx',
        ),
    ]
