# Generated by Django 5.2.3 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_rename_legal_legald_slug_versi_b7f135_idx_legal_legal_slug_ad8e2d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsent",
            name="is_valid",
            field=models.BooleanField(default=True, help_text="Marcado en falso cuando hay nueva versión del documento o se revoca."),
        ),
    ]
