import pytest
from django.utils import timezone
from model_bakery import baker

from spa.models import Package, UserPackage, Voucher, ServiceCategory, Service


@pytest.mark.django_db
def test_voucher_code_autogenerated_and_expires_with_package():
    category = baker.make(ServiceCategory)
    service = baker.make(Service, category=category)
    package = baker.make(Package, validity_days=30)
    user_package = baker.make(UserPackage, package=package)

    voucher = Voucher.objects.create(
        user_package=user_package,
        user=user_package.user,
        service=service,
    )

    assert voucher.code  # auto generated
    assert voucher.expires_at is not None
    assert voucher.expires_at >= timezone.now().date()
