# Generated by Django 5.2.3 on 2025-11-16 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Carrito Activo')),
            ],
            options={
                'verbose_name': 'Carrito de Compras',
                'verbose_name_plural': 'Carritos de Compras',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Ítem de Carrito',
                'verbose_name_plural': 'Ítems de Carrito',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Pagada'), ('PREPARING', 'En Preparación'), ('SHIPPED', 'Enviada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada'), ('RETURNED', 'Devuelta')], default='PENDING_PAYMENT', max_length=20, verbose_name='Estado de la Orden')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('delivery_option', models.CharField(choices=[('PICKUP', 'Recogida en Local'), ('DELIVERY', 'Envío a Domicilio'), ('ASSOCIATE_TO_APPOINTMENT', 'Asociar a Cita Futura')], max_length=30, verbose_name='Opción de Entrega')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Dirección de Envío')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Seguimiento')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transacción Wompi')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al Comprar')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='Cantidad Devuelta')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está visible y disponible para la compra.', verbose_name='Activo')),
                ('preparation_days', models.PositiveSmallIntegerField(default=1, verbose_name='Días de Preparación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Identifica la presentación, por ejemplo 50ml.', max_length=120, verbose_name='Nombre de la Variante')),
                ('sku', models.CharField(help_text='Identificador único para integraciones y carrito.', max_length=60, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Regular')),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento para miembros VIP. Dejar en blanco si no aplica.', max_digits=10, null=True, verbose_name='Precio para VIPs')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['product__name', 'name'],
            },
        ),
    ]
