# Generated by Django 5.2.3 on 2025-11-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de devolución'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_request_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Pagada'), ('PREPARING', 'En Preparación'), ('SHIPPED', 'Enviada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada'), ('RETURN_REQUESTED', 'Devolución Solicitada'), ('RETURN_APPROVED', 'Devolución Aprobada'), ('RETURN_REJECTED', 'Devolución Rechazada'), ('REFUNDED', 'Reembolsada')], default='PENDING_PAYMENT', max_length=20, verbose_name='Estado de la Orden'),
        ),
    ]
