# Generated by Django 5.2.3 on 2025-11-16 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_return_reason_order_return_request_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Pagada'), ('PREPARING', 'En Preparación'), ('SHIPPED', 'Enviada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada'), ('RETURN_REQUESTED', 'Devolución Solicitada'), ('RETURN_APPROVED', 'Devolución Aprobada'), ('RETURN_REJECTED', 'Devolución Rechazada'), ('REFUNDED', 'Reembolsada'), ('FRAUD_ALERT', 'Alerta de Fraude')], default='PENDING_PAYMENT', max_length=20, verbose_name='Estado de la Orden'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('SALE', 'Venta'), ('RETURN', 'Devolución'), ('RESTOCK', 'Reabastecimiento'), ('ADJUSTMENT', 'Ajuste'), ('EXPIRED_RESERVATION', 'Reserva expirada')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL)),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='marketplace.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='marketplace.productvariant')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
