# Generated by Django 5.2.3 on 2025-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_delivered_at_order_fraud_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Reservado'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Venta'), ('RETURN', 'Devolución'), ('RESTOCK', 'Reabastecimiento'), ('ADJUSTMENT', 'Ajuste'), ('RESERVATION', 'Reserva creada'), ('RESERVATION_RELEASE', 'Reserva liberada'), ('EXPIRED_RESERVATION', 'Reserva expirada')], max_length=20),
        ),
    ]
