# Generated by Django 5.2.3 on 2025-11-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_reservations_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Avisar al admin cuando el stock baje de esta cantidad.', verbose_name='Umbral de Stock Bajo'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='max_order_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Máximo por Orden'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_order_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Mínimo por Orden'),
        ),
    ]
