# Generated by Django 5.2.3 on 2025-11-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_cart_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para considerar el carrito antes de limpiarlo.', null=True, verbose_name='Expira el'),
        ),
    ]
