# Generated by Django 5.2.3 on 2025-11-29 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_cart_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título de la Reseña')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Indica si esta reseña proviene de una compra confirmada', verbose_name='Compra Verificada')),
                ('is_approved', models.BooleanField(default=True, help_text='Los administradores pueden moderar reseñas inapropiadas', verbose_name='Aprobada')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del Administrador')),
                ('order', models.ForeignKey(blank=True, help_text='Orden que valida que el usuario compró el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='marketplace.order', verbose_name='Orden de Compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas de Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='marketplace_product_5b53e6_idx'), models.Index(fields=['rating'], name='marketplace_rating_26b4a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_review_per_user_per_product')],
            },
        ),
    ]
