# Generated by Django 5.2.3 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_productreview"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.UniqueConstraint(
                fields=("movement_type", "reference_order", "variant"),
                name="unique_movement_per_order_variant_type",
            ),
        ),
    ]
