# Generated by Django 5.2.3 on 2025-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_inventorymovement_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío aplicado a esta orden', max_digits=10, verbose_name='Costo de Envío'),
        ),
    ]
