# Generated by Django 5.2.3 on 2025-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_add_shipping_cost_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Beneficios del producto para la piel o salud.', verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='Instrucciones de aplicación o uso del producto.', verbose_name='Modo de Uso'),
        ),
        migrations.AddField(
            model_name='product',
            name='what_is_included',
            field=models.TextField(blank=True, help_text='Detalle de qué incluye el producto (ingredientes, componentes, etc.)', verbose_name='Qué Incluye'),
        ),
    ]
