# Generated by Django 5.2.3 on 2026-01-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto para optimización en frontend (prioridad sobre ProductImage).', max_length=500, null=True, verbose_name='URL de Imagen Externa'),
        ),
    ]
