# Generated by Django 5.2.3 on 2026-01-07 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'display_order', 'created_at'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en el que se muestra la imagen (menor = primero)', verbose_name='Orden de Visualización'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa. Se usa si no hay archivo subido.', max_length=500, null=True, verbose_name='URL de Imagen Externa'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen o proporciona una URL externa.', null=True, upload_to='product_images/', verbose_name='Imagen (archivo)'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='URL de la imagen para esta variante.', max_length=500, verbose_name='URL de Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en el que se muestra la imagen (menor = primero)', verbose_name='Orden de Visualización')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Imagen de Variante',
                'verbose_name_plural': 'Imágenes de Variantes',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
