# Generated by Django 5.2.3 on 2025-12-27 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título principal de la promoción (ej: '¡DESCUENTO ESPECIAL!')", max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada. Puedes usar HTML básico (<b>, <i>, <br>, etc.)')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen promocional (opcional). Tamaño recomendado: 800x600px', null=True, upload_to='promociones/')),
                ('tipo', models.CharField(choices=[('popup', 'Pop-up'), ('banner', 'Banner Superior')], default='popup', help_text='Tipo de visualización de la promoción', max_length=20)),
                ('paginas', models.JSONField(default=list, help_text="Lista de páginas donde se mostrará (ej: ['dashboard', 'home'])")),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, se mostrará a los usuarios')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio (opcional). Si se deja vacío, inicia inmediatamente', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización (opcional). Si se deja vacío, no caduca', null=True)),
                ('mostrar_siempre', models.BooleanField(default=False, help_text='Si es False, el pop-up se muestra solo 1 vez por sesión (usa localStorage)')),
                ('prioridad', models.IntegerField(default=0, help_text='Mayor prioridad = se muestra primero (si hay múltiples activas). 0 = menor prioridad', validators=[django.core.validators.MinValueValidator(0)])),
                ('veces_mostrada', models.IntegerField(default=0, editable=False, help_text='Contador automático de veces que se ha mostrado')),
                ('veces_clickeada', models.IntegerField(default=0, editable=False, help_text='Contador automático de clics en el botón de acción')),
                ('link_accion', models.CharField(blank=True, help_text="URL interna o externa (ej: '/servicios' o 'https://...')", max_length=500)),
                ('texto_boton', models.CharField(default='Ver más', help_text='Texto del botón de acción', max_length=50)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-prioridad', '-creada_en'],
            },
        ),
    ]
