# Generated by Django 5.2.3 on 2025-12-27 23:51

from django.db import migrations


def actualizar_servicios_a_services(apps, schema_editor):
    """
    Actualiza 'servicios' a 'services' en el campo paginas (JSONField)
    para todas las promociones existentes.
    """
    Promocion = apps.get_model('promociones', 'Promocion')

    for promo in Promocion.objects.all():
        if promo.paginas and 'servicios' in promo.paginas:
            # Reemplazar 'servicios' por 'services'
            promo.paginas = [
                'services' if p == 'servicios' else p
                for p in promo.paginas
            ]
            promo.save()
            print(f"✓ Actualizada promoción '{promo.titulo}': servicios → services")


def revertir_services_a_servicios(apps, schema_editor):
    """
    Función para revertir el cambio si es necesario.
    """
    Promocion = apps.get_model('promociones', 'Promocion')

    for promo in Promocion.objects.all():
        if promo.paginas and 'services' in promo.paginas:
            # Revertir 'services' a 'servicios'
            promo.paginas = [
                'servicios' if p == 'services' else p
                for p in promo.paginas
            ]
            promo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            actualizar_servicios_a_services,
            reverse_code=revertir_services_a_servicios
        ),
    ]
