# Generated by Django 5.2.3 on 2025-12-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_update_servicios_to_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen externa (opcional). Tiene prioridad sobre la imagen subida.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen subida localmente (opcional).', null=True, upload_to='promociones/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='paginas',
            field=models.JSONField(default=list, help_text="Lista de páginas donde se mostrará (ej: ['dashboard', 'home', 'services', 'shop', 'book'])"),
        ),
    ]
