# Generated by Django 5.2.3 on 2025-07-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='attended_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='spa.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(related_name='packages', to='spa.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='spa.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Category the service belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='spa.servicecategory'),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='staff_member',
            field=models.ForeignKey(limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff_member', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
