# Generated by Django 5.2.3 on 2025-07-18 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price_at_booking',
        ),
        migrations.AddField(
            model_name='appointment',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo'), ('FINAL', 'Pago Final'), ('FULL', 'Pago Completo')], default='FULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attended_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_ADVANCE', 'Pendiente de Pago de Anticipo'), ('CONFIRMED', 'Confirmada (Anticipo Pagado)'), ('COMPLETED_PENDING_FINAL_PAYMENT', 'Completada (Pago Final Pendiente)'), ('COMPLETED', 'Completada y Pagada'), ('CANCELLED_BY_CLIENT', 'Cancelada por el Cliente'), ('CANCELLED_BY_SYSTEM', 'Cancelada por el Sistema'), ('CANCELLED_BY_ADMIN', 'Cancelada por el Administrador')], default='PENDING_ADVANCE', max_length=40),
        ),
    ]
