# Generated by Django 5.2.3 on 2025-07-23 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error'), ('PAID_WITH_CREDIT', 'Pagado con Saldo a Favor')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PARTIALLY_USED', 'Parcialmente Usado'), ('FULLY_USED', 'Totalmente Usado'), ('EXPIRED', 'Expirado')], default='AVAILABLE', max_length=20)),
                ('expires_at', models.DateField()),
                ('originating_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_credit', to='spa.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo a Favor de Cliente',
                'verbose_name_plural': 'Saldos a Favor de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='used_credit',
            field=models.ForeignKey(blank=True, help_text='Crédito de cliente que se utilizó para cubrir este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_covered', to='spa.clientcredit'),
        ),
    ]
