# Generated by Django 5.2.3 on 2025-11-16 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('WAITING', 'En espera'), ('OFFERED', 'Oferta enviada'), ('EXPIRED', 'Oferta expirada'), ('CONFIRMED', 'Confirmada')], default='WAITING', max_length=10)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offered_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_offers', to='spa.appointment')),
                ('services', models.ManyToManyField(blank=True, related_name='waitlist_entries', to='spa.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Lista de Espera',
                'verbose_name_plural': 'Lista de Espera',
                'ordering': ['created_at'],
            },
        ),
    ]
