# Generated by Django 5.2.3 on 2025-11-16 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_waitlistentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcredit',
            name='originating_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_credit', to='spa.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo de Cita'), ('FINAL', 'Pago Final de Cita'), ('PACKAGE', 'Compra de Paquete'), ('VIP_SUBSCRIPTION', 'Suscripción VIP'), ('TIP', 'Propina')], max_length=16),
        ),
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_type', models.CharField(choices=[('CREDIT', 'Nota Crédito'), ('DEBIT', 'Nota Débito')], max_length=6)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_adjustments', to='spa.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Financiero',
                'verbose_name_plural': 'Ajustes Financieros',
                'ordering': ['-created_at'],
            },
        ),
    ]
