# Generated by Django 5.2.3 on 2025-11-16 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_availabilityexclusion_historicalservice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PROCESSED', 'Procesado'), ('FAILED', 'Fallido'), ('IGNORED', 'Ignorado')], default='PROCESSED', max_length=12)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error'), ('TIMEOUT', 'Sin confirmación'), ('PAID_WITH_CREDIT', 'Pagado con Saldo a Favor')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='LoyaltyRewardLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rewarded_at', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_reward', to='spa.voucher')),
            ],
            options={
                'verbose_name': 'Recompensa de Lealtad',
                'verbose_name_plural': 'Recompensas de Lealtad',
                'ordering': ['-rewarded_at'],
            },
        ),
    ]
