# Generated by Django 5.2.3 on 2025-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_webhookevent_voucher_expires_at_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
