# Generated by Django 5.2.3 on 2025-11-17 06:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_servicecategory_service_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
                ('all_objects', core.models.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='servicecategory',
            managers=[
                ('objects', core.models.SoftDeleteManager()),
                ('all_objects', core.models.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalservicecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalservicecategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
