# Generated by Django 5.2.3 on 2025-11-18 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_reservations_fields'),
        ('spa', '0008_alter_service_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('NONE', 'Sin resultado'), ('CANCELLED_BY_CLIENT', 'Cancelada por el Cliente'), ('CANCELLED_BY_SYSTEM', 'Cancelada por el Sistema'), ('CANCELLED_BY_ADMIN', 'Cancelada por el Administrador'), ('NO_SHOW', 'No Asistió'), ('REFUNDED', 'Reembolsada')], default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.order'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Pago Final Pendiente'), ('CONFIRMED', 'Confirmada'), ('RESCHEDULED', 'Reagendada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING_PAYMENT', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo de Cita'), ('FINAL', 'Pago Final de Cita'), ('PACKAGE', 'Compra de Paquete'), ('VIP_SUBSCRIPTION', 'Suscripción VIP'), ('TIP', 'Propina'), ('ORDER', 'Compra Marketplace')], max_length=16),
        ),
        migrations.CreateModel(
            name='PaymentCreditUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usages', to='spa.clientcredit')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usages', to='spa.payment')),
            ],
            options={
                'verbose_name': 'Uso de Crédito en Pago',
                'verbose_name_plural': 'Usos de Créditos en Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
