# Generated by Django 4.2.7 on 2024-11-27 12:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_appointment_outcome_payment_order_and_more'),
    ]

    operations = [
        # This migration is intentionally empty to fix the gap between 0009 and 0011
    ]
