# Generated by Django 5.2.3 on 2025-11-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_estimated_delivery_date_and_more'),
        ('spa', '0011_add_wompi_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcredit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financialadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loyaltyrewardlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentcreditusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['expires_at']},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='redeemed_appointment',
        ),
        migrations.AlterField(
            model_name='clientcredit',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Fecha de expiración del crédito.', null=True),
        ),
        migrations.AlterField(
            model_name='clientcredit',
            name='originating_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_credits', to='spa.payment'),
        ),
        migrations.AlterField(
            model_name='clientcredit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PARTIALLY_USED', 'Parcialmente Usado'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], default='CREDIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_related', to='spa.payment'),
        ),
        migrations.AlterField(
            model_name='loyaltyrewardlog',
            name='rewarded_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loyaltyrewardlog',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='spa.voucher'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='spa.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo de Cita'), ('FINAL', 'Pago Final de Cita'), ('PACKAGE', 'Compra de Paquete'), ('TIP', 'Propina'), ('VIP_SUBSCRIPTION', 'Membresía VIP'), ('ORDER', 'Orden de Marketplace')], default='ADVANCE', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='Reference/transaction id from the payment gateway.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='used_credit',
            field=models.ForeignKey(blank=True, help_text='Crédito usado en este pago (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_payments', to='spa.clientcredit'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentcreditusage',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_usages', to='spa.clientcredit'),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_logs', to='spa.payment'),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='expires_at',
            field=models.DateField(help_text='Fecha en la que expiran los vouchers de este paquete.'),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_packages', to='spa.package'),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='spa.service'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='user_package',
            field=models.ForeignKey(blank=True, help_text='Paquete de origen del voucher.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='spa.userpackage'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Procesado'), ('FAILED', 'Falló'), ('IGNORED', 'Ignorado')], default='PROCESSED', max_length=20),
        ),
    ]
