# Generated by Django 5.2.3 on 2025-11-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_add_payment_models'),
        ('spa', '0012_alter_clientcredit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcredit',
            name='originating_payment',
        ),
        migrations.RemoveField(
            model_name='clientcredit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentcreditusage',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='used_credit',
        ),
        migrations.RemoveField(
            model_name='financialadjustment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financialadjustment',
            name='related_payment',
        ),
        migrations.RemoveField(
            model_name='financialadjustment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentcreditusage',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='subscriptionlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
        migrations.DeleteModel(
            name='ClientCredit',
        ),
        migrations.DeleteModel(
            name='FinancialAdjustment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentCreditUsage',
        ),
        migrations.DeleteModel(
            name='SubscriptionLog',
        ),
    ]
