# Generated by Django 5.2.3 on 2025-11-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_auto_fix_missing'),
        ('spa', '0013_add_payment_models'),
    ]

    operations = [
    ]
