# Generated by Django 5.2.3 on 2025-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0015_add_analytics_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='benefits',
            field=models.TextField(blank=True, help_text='Beneficios para la piel (e.g. hidratación, luminosidad)'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Contraindicaciones médicas o de salud.'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='what_is_included',
            field=models.TextField(blank=True, help_text='Detalle de qué incluye el servicio (pasos, productos, etc.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='Beneficios para la piel (e.g. hidratación, luminosidad)'),
        ),
        migrations.AddField(
            model_name='service',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Contraindicaciones médicas o de salud.'),
        ),
        migrations.AddField(
            model_name='service',
            name='what_is_included',
            field=models.TextField(blank=True, help_text='Detalle de qué incluye el servicio (pasos, productos, etc.)'),
        ),
    ]
