# Generated by Django 5.2.3 on 2025-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0016_historicalservice_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Esperando Pago Final'), ('CONFIRMED', 'Confirmada'), ('FULLY_PAID', 'Totalmente Pagado'), ('RESCHEDULED', 'Reagendada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING_PAYMENT', max_length=40),
        ),
    ]
