# Generated by Django 5.2.3 on 2025-12-26 17:31

from django.db import migrations, models


def convert_paid_to_confirmed(apps, schema_editor):
    """
    Convert all appointments with status='PAID' to status='CONFIRMED'.

    Rationale:
    - PAID status was semantically confusing (meant "awaiting final payment")
    - Now we use CONFIRMED for appointments with outstanding balance
    - The outstanding_balance property shows remaining debt
    """
    Appointment = apps.get_model('spa', 'Appointment')

    updated_count = Appointment.objects.filter(status='PAID').update(status='CONFIRMED')

    if updated_count > 0:
        print(f"Converted {updated_count} appointments from PAID to CONFIRMED")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - convert CONFIRMED back to PAID if needed.
    Note: This is a lossy operation since we can't distinguish which
    CONFIRMED appointments were originally PAID.
    """
    # We cannot reliably reverse this, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0017_add_fully_paid_status'),
    ]

    operations = [
        migrations.RunPython(convert_paid_to_confirmed, reverse_migration),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_PAYMENT', 'Pendiente de Pago'),
                    ('CONFIRMED', 'Confirmada'),
                    ('FULLY_PAID', 'Totalmente Pagado'),
                    ('RESCHEDULED', 'Reagendada'),
                    ('COMPLETED', 'Completada'),
                    ('CANCELLED', 'Cancelada'),
                ],
                max_length=50,
            ),
        ),
    ]
