# Generated by Django 5.2.3 on 2026-01-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_add_payment_fields_to_commission_ledger'),
        ('spa', '0018_remove_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyrewardlog',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards', to='finances.clientcredit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('CONFIRMED', 'Confirmada'), ('FULLY_PAID', 'Totalmente Pagado'), ('RESCHEDULED', 'Reagendada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING_PAYMENT', max_length=40),
        ),
    ]
