# Generated by Django 5.2.3 on 2026-01-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0019_loyaltyrewardlog_credit_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen del servicio (para optimización en frontend).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen del servicio (para optimización en frontend).', max_length=500, null=True),
        ),
    ]
