# Generated by Django 5.2.3 on 2026-01-08 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0020_historicalservice_image_url_service_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='is_main_media_video',
            field=models.BooleanField(default=False, help_text='Indica si el medio principal es un video en lugar de una imagen.', verbose_name='¿El medio principal es un video?'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='main_media_url',
            field=models.URLField(blank=True, help_text='URL externa del medio principal del servicio (imagen o video). Prioridad sobre ServiceMedia.', max_length=500, null=True, verbose_name='URL de Imagen/Video Principal'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_main_media_video',
            field=models.BooleanField(default=False, help_text='Indica si el medio principal es un video en lugar de una imagen.', verbose_name='¿El medio principal es un video?'),
        ),
        migrations.AddField(
            model_name='service',
            name='main_media_url',
            field=models.URLField(blank=True, help_text='URL externa del medio principal del servicio (imagen o video). Prioridad sobre ServiceMedia.', max_length=500, null=True, verbose_name='URL de Imagen/Video Principal'),
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_url', models.URLField(help_text='URL de la imagen o video para este servicio.', max_length=500, verbose_name='URL del Medio')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], default='IMAGE', help_text='Tipo de medio: imagen o video.', max_length=10, verbose_name='Tipo de Medio')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción del medio para accesibilidad.', max_length=255, verbose_name='Texto Alternativo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en el que se muestra el medio (menor = primero)', verbose_name='Orden de Visualización')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='spa.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Medio de Servicio',
                'verbose_name_plural': 'Medios de Servicio',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['service', 'display_order'], name='spa_service_service_777525_idx')],
            },
        ),
    ]
