# Generated by Django 5.2.3 on 2025-12-14 00:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/', verbose_name='Imagen de portada')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo de portada')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del autor (override)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta título (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción (SEO)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Tiempo de lectura (minutos)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='Orden destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Categoría')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/content/%Y/%m/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Imagen de artículo',
                'verbose_name_plural': 'Imágenes de artículos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('cover_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen de portada')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo de portada')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del autor (override)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta título (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta descripción (SEO)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Tiempo de lectura (minutos)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='Orden destacado')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.category', verbose_name='Categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Artículo',
                'verbose_name_plural': 'historical Artículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at', 'status'], name='blog_articl_publish_a4ba74_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', '-featured_order'], name='blog_articl_is_feat_ef8a8c_idx'),
        ),
    ]
