# Generated by Django 5.2.3 on 2026-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen de portada'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen de portada'),
        ),
    ]
