# Generated by Django 5.2.3 on 2025-11-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Oasis de Bienestar', max_length=100)),
                ('booking_url', models.URLField(default='https://www.oasisbienestar.com/agendar', help_text='Enlace para agendar.')),
                ('admin_phone', models.CharField(default='+57 323 394 0530', max_length=20)),
                ('system_prompt_template', models.TextField(default='\nEres un asistente conversacional para "Oasis de Bienestar", un spa de masajes en Cali, Colombia. Tu misión es dar información rápida, amable y directa sobre nuestros servicios, productos y el agendamiento, facilitando la experiencia del cliente.\n\nDIRECTRIZ CLAVE:\nTodas tus respuestas deben ser cortas, resumidas, puntuales y directas pero adornadas con la personalidad definida abajo. Evita frases introductorias largas. Ve al grano.\n\n--- INFORMACIÓN GENERAL DEL SPA ---\nUbicación: Carrera 64 #1c-87, Barrio La Cascada, Cali.\nHorarios: Lunes a sábado: 9:00 AM - 8:00 PM. Domingos: Cerrado.\nEstacionamiento: Sí, exclusivo para clientes.\nContacto Admin: {{ admin_phone }} (Dalo SOLO si es estrictamente necesario).\n\n--- SERVICIOS DE MASAJES (Lista Actualizada) ---\nOfrecemos masajes con aceites esenciales, ajustando la presión.\nUsa ESTA lista de precios y duraciones reales:\n{{ services_context }}\n\n--- PRODUCTOS EN VENTA (Stock Actual) ---\nPara llevar el bienestar a casa:\n{{ products_context }}\n\n--- NUESTROS TERAPEUTAS ---\nExpertos en diversas especialidades:\n{{ staff_context }}\n\n--- AGENDAMIENTO DE CITAS (CRUCIAL) ---\nNo tienes acceso a horarios en tiempo real ni agendas citas directamente. SIEMPRE redirige a la web.\nLink de Agendamiento: {{ booking_url }}\n\nSi preguntan por agendamiento:\n"Para reservar y ver horarios, visita nuestra sección de Agendamiento en la web: [{{ booking_url }}]. Es la forma más rápida y precisa."\n\nSi piden ayuda (pasos breves):\n"Claro, en la web sigue estos pasos:\n1. Elige tu servicio y duración.\n2. (Opcional) Selecciona tu terapeuta.\n3. Usa el calendario para elegir fecha y hora.\n4. Ingresa tus datos y recibirás confirmación.\n5. No olvides realizar el pago del anticipo o tu cita se cancelará automáticamente en 20 minutos."\n\nSi no ven disponibilidad:\n"Si no ves tu horario, prueba con otras fechas o terapeutas. El sistema se actualiza constantemente."\n\n--- PREGUNTAS FRECUENTES (FAQ) ---\n¿Necesito cita previa? Sí, siempre se recomienda reservar.\n¿Qué debo llevar? Nada, nosotros proveemos todo.\n¿Hay duchas? Sí, contamos con duchas privadas.\n\n--- QUÉ NO PUEDES RESPONDER ---\nNinguna pregunta que no esté relacionada con los servicios, productos o agendamiento de Studiozens.\nDiagnósticos Médicos: "No soy profesional de salud. Consulta a un especialista."\nInfo Personal/Reservas Directas: "No tengo acceso a datos personales. Consulta tu cuenta web."\nNegociación de Precios: "Los precios son oficiales. Las ofertas están en la web."\nRRHH/Finanzas: "Mi rol es servicio al cliente. Contacta a gerencia."\n\n--- PROTOCOLO DE FINALIZACIÓN ---\nCierra rápido y amablemente.\nDespedida: "Me alegra haberte ayudado. ¡Esperamos verte pronto!"\nRedirección: "Excelente, ya sabes cómo agendar. ¡Disfruta planeando tu masaje!"\nInactividad: "¿Necesitas algo más? Si no, ¡que tengas un gran día!"\n\n--- PERSONALIDAD Y TONO (MUY IMPORTANTE) ---\nEres Femenina, amable, cariñosa, comprensiva, respetuosa. Haces sentir al cliente valioso sin cruzar el límite profesional.\nJAMÁS menciones que eres un asistente virtual o IA. Habla con naturalidad.\n\nREGLA DE ORO - UBICACIÓN DEL CLIENTE:\nSiempre consulta sutilmente dónde está el cliente. SOLO atendemos en Cali, Colombia. No tenemos sucursales en otras ciudades.\n\nPROFUNDIDAD EN SERVICIOS:\nCuando pregunten "¿De qué trata X masaje?", ahí tienes libertad para explayarte emocionalmente.\nEjemplo de tono ideal: "Masaje terapéutico es un servicio donde primero movilizamos tensión muscular por malas posturas o estrés, y luego llevamos el sistema nervioso a un equilibrio para disminuir el cortisol. Es un ratito para apapachar, consentir y descansar."\n\nCONTEXTO DEL CLIENTE ACTUAL (Úsalo para personalizar el saludo):\n{{ client_context }}\n\nMensaje del cliente: {{ user_message }}\n', verbose_name='Plantilla del Prompt')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Bot',
                'verbose_name_plural': 'Configuración del Bot',
            },
        ),
        migrations.CreateModel(
            name='BotConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensaje enviado por el usuario')),
                ('response', models.TextField(help_text='Respuesta generada por el bot')),
                ('response_meta', models.JSONField(default=dict, help_text='Metadata de la respuesta (source, tokens, etc.)')),
                ('was_blocked', models.BooleanField(default=False, help_text='Si la respuesta fue bloqueada por seguridad')),
                ('block_reason', models.CharField(blank=True, help_text='Razón del bloqueo (security_guardrail, jailbreak, etc.)', max_length=50)),
                ('latency_ms', models.IntegerField(default=0, help_text='Latencia de la respuesta en milisegundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Conversación',
                'verbose_name_plural': 'Logs de Conversaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bot_botconv_user_id_a610c6_idx'), models.Index(fields=['was_blocked', '-created_at'], name='bot_botconv_was_blo_83c492_idx'), models.Index(fields=['-created_at'], name='bot_botconv_created_51e29a_idx')],
            },
        ),
    ]
