# Generated by Django 5.2.3 on 2025-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversationlog',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Tokens consumidos en esta conversación (prompt + completion)'),
        ),
    ]
