# Generated by Django 5.2.3 on 2025-11-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_add_tokens_used_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='api_input_price_per_1k',
            field=models.DecimalField(decimal_places=6, default=0.0001, help_text='Costo de tokens de entrada. Gemini 1.5 Flash: $0.0001 ($0.10/1M)', max_digits=10, verbose_name='Precio Input (USD/1K tokens)'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='api_output_price_per_1k',
            field=models.DecimalField(decimal_places=6, default=0.0004, help_text='Costo de tokens de salida. Gemini 1.5 Flash: $0.0004 ($0.40/1M)', max_digits=10, verbose_name='Precio Output (USD/1K tokens)'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='avg_tokens_alert_threshold',
            field=models.IntegerField(default=2000, help_text='Alertar si el promedio de tokens por conversación excede este valor', verbose_name='Umbral de Tokens Promedio'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='daily_cost_alert_threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Enviar alerta si el costo diario excede este valor', max_digits=10, verbose_name='Umbral de Alerta Diaria (USD)'),
        ),
    ]
