# Generated by Django 5.2.3 on 2025-11-23 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_add_configurable_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiguration',
            name='daily_cost_alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0.33, help_text='Enviar alerta si el costo diario excede este valor', max_digits=10, verbose_name='Umbral de Alerta Diaria (USD)'),
        ),
        migrations.AlterField(
            model_name='botconversationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario registrado (null si es anónimo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único de sesión para trackear usuario anónimo', unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del usuario anónimo')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración de la sesión (30 días)')),
                ('converted_to_user', models.ForeignKey(blank=True, help_text='Usuario registrado al que se convirtió este anónimo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_anonymous_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Anónimo',
                'verbose_name_plural': 'Usuarios Anónimos',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='botconversationlog',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, help_text='Usuario anónimo (null si es registrado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to='bot.anonymoususer'),
        ),
        migrations.AddIndex(
            model_name='botconversationlog',
            index=models.Index(fields=['anonymous_user', '-created_at'], name='bot_botconv_anonymo_4e8d03_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['session_id'], name='bot_anonymo_session_c0e934_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['ip_address', '-created_at'], name='bot_anonymo_ip_addr_02e5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['-last_activity'], name='bot_anonymo_last_ac_aae4b8_idx'),
        ),
    ]
