# Generated by Django 5.2.3 on 2025-11-24 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_botconfiguration_daily_cost_alert_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanHandoffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_score', models.IntegerField(default=0, help_text='Score del cliente (0-100) basado en valor potencial')),
                ('escalation_reason', models.CharField(choices=[('EXPLICIT_REQUEST', 'Solicitud Explícita del Cliente'), ('FRUSTRATION_DETECTED', 'Frustración Detectada'), ('HIGH_VALUE_CLIENT', 'Cliente de Alto Valor')], help_text='Razón del escalamiento', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelto'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado actual de la solicitud', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_context', models.JSONField(default=dict, help_text='Resumen de la conversación hasta el momento del escalamiento')),
                ('client_interests', models.JSONField(default=dict, help_text='Servicios/productos consultados, presupuesto mencionado, etc.')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Notas internas del staff sobre el cliente')),
                ('anonymous_user', models.ForeignKey(blank=True, help_text='Usuario anónimo (null si es registrado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoff_requests', to='bot.anonymoususer')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handoffs', to=settings.AUTH_USER_MODEL)),
                ('conversation_log', models.ForeignKey(blank=True, help_text='Log de la conversación que generó el escalamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_requests', to='bot.botconversationlog')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado (null si es anónimo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoff_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Atención Humana',
                'verbose_name_plural': 'Solicitudes de Atención Humana',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_anonymous', models.BooleanField(default=False, help_text='True si el mensaje es de un cliente anónimo')),
                ('is_from_staff', models.BooleanField(default=False, help_text='True si el mensaje es del staff, False si es del cliente')),
                ('message', models.TextField(help_text='Contenido del mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Momento en que el mensaje fue leído', null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs de archivos adjuntos (imágenes, documentos, etc.)')),
                ('handoff_request', models.ForeignKey(help_text='Solicitud de handoff asociada', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.humanhandoffrequest')),
                ('sender', models.ForeignKey(help_text='Usuario que envía el mensaje (staff o cliente registrado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje Humano',
                'verbose_name_plural': 'Mensajes Humanos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='humanhandoffrequest',
            index=models.Index(fields=['status', '-created_at'], name='bot_humanha_status_65ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='humanhandoffrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='bot_humanha_assigne_9811ac_idx'),
        ),
        migrations.AddIndex(
            model_name='humanhandoffrequest',
            index=models.Index(fields=['user', '-created_at'], name='bot_humanha_user_id_52e7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='humanhandoffrequest',
            index=models.Index(fields=['anonymous_user', '-created_at'], name='bot_humanha_anonymo_b3bc26_idx'),
        ),
        migrations.AddIndex(
            model_name='humanhandoffrequest',
            index=models.Index(fields=['-client_score'], name='bot_humanha_client__a90868_idx'),
        ),
        migrations.AddIndex(
            model_name='humanmessage',
            index=models.Index(fields=['handoff_request', 'created_at'], name='bot_humanme_handoff_85c1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='humanmessage',
            index=models.Index(fields=['is_from_staff', 'created_at'], name='bot_humanme_is_from_845a78_idx'),
        ),
        migrations.AddIndex(
            model_name='humanmessage',
            index=models.Index(fields=['read_at'], name='bot_humanme_read_at_d493c5_idx'),
        ),
    ]
