# Generated by Django 5.2.3 on 2025-11-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_botconversationlog_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP bloqueada', unique=True)),
                ('reason', models.CharField(choices=[('ABUSE', 'Abuso de Límites'), ('MALICIOUS_CONTENT', 'Contenido Malicioso'), ('SPAM', 'Spam/Flooding'), ('FRAUD', 'Fraude Detectado'), ('MANUAL', 'Bloqueo Manual por Admin')], help_text='Razón del bloqueo', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Notas internas sobre el bloqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del bloqueo (null = permanente)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el bloqueo está activo')),
                ('blocked_by', models.ForeignKey(help_text='Admin que bloqueó la IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='bot_ipblock_ip_addr_8b68c6_idx'), models.Index(fields=['-created_at'], name='bot_ipblock_created_a33ae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde donde se realizó la actividad sospechosa')),
                ('activity_type', models.CharField(choices=[('RATE_LIMIT_HIT', 'Límite de Velocidad Alcanzado'), ('DAILY_LIMIT_HIT', 'Límite Diario Alcanzado'), ('REPETITIVE_MESSAGES', 'Mensajes Repetitivos'), ('JAILBREAK_ATTEMPT', 'Intento de Jailbreak'), ('MALICIOUS_CONTENT', 'Contenido Malicioso'), ('OFF_TOPIC_SPAM', 'Spam Fuera de Tema'), ('EXCESSIVE_TOKENS', 'Uso Excesivo de Tokens'), ('IP_ROTATION', 'Rotación de IP Sospechosa')], help_text='Tipo de actividad sospechosa detectada', max_length=30)),
                ('severity', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=2, help_text='Nivel de severidad de la actividad')),
                ('description', models.TextField(help_text='Descripción detallada de la actividad sospechosa')),
                ('context', models.JSONField(default=dict, help_text='Contexto adicional: mensaje enviado, respuesta, metadata, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Si un admin ya revisó esta actividad')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha de revisión', null=True)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Notas del admin sobre esta actividad')),
                ('anonymous_user', models.ForeignKey(blank=True, help_text='Usuario anónimo (null si es registrado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='bot.anonymoususer')),
                ('conversation_log', models.ForeignKey(blank=True, help_text='Log de conversación asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='bot.botconversationlog')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin que revisó la actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado (null si es anónimo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad Sospechosa',
                'verbose_name_plural': 'Actividades Sospechosas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='bot_suspici_ip_addr_13d119_idx'), models.Index(fields=['user', '-created_at'], name='bot_suspici_user_id_df1f71_idx'), models.Index(fields=['anonymous_user', '-created_at'], name='bot_suspici_anonymo_cc8d5d_idx'), models.Index(fields=['activity_type', '-created_at'], name='bot_suspici_activit_7cde4b_idx'), models.Index(fields=['severity', '-created_at'], name='bot_suspici_severit_675d34_idx'), models.Index(fields=['reviewed', '-created_at'], name='bot_suspici_reviewe_108bf1_idx')],
            },
        ),
    ]
