# Generated by Django 5.2.3 on 2025-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_ipblocklist_suspiciousactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='auto_block_analysis_period_hours',
            field=models.IntegerField(default=24, help_text='Ventana de tiempo para contar actividades críticas', verbose_name='Período de Análisis (horas)'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='auto_block_critical_threshold',
            field=models.IntegerField(default=3, help_text='Número de actividades críticas antes de bloquear automáticamente', verbose_name='Umbral de Actividades Críticas'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='enable_auto_block',
            field=models.BooleanField(default=True, help_text='Bloquear automáticamente IPs con comportamiento abusivo', verbose_name='Habilitar Auto-Bloqueo'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='enable_critical_alerts',
            field=models.BooleanField(default=True, help_text='Enviar email cuando se detecten actividades críticas', verbose_name='Habilitar Alertas Críticas'),
        ),
    ]
