# Generated by Django 5.2.3 on 2025-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_botconfiguration_system_prompt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanhandoffrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelto'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado por Tiempo')], default='PENDING', help_text='Estado actual de la solicitud', max_length=20),
        ),
    ]
