# Generated by Django 5.2.3 on 2025-11-24 13:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spa', '0009_appointment_outcome_payment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto adeudado al desarrollador por esta transacción.', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total aplicado a esta comisión.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('FAILED_NSF', 'Fondos insuficientes')], default='PENDING', max_length=20)),
                ('wompi_transfer_id', models.CharField(blank=True, help_text='Identificador de la dispersión en Wompi cuando se pague.', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Momento en que la comisión fue liquidada.', null=True)),
                ('source_payment', models.ForeignKey(help_text='Pago original que generó la comisión.', on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='spa.payment')),
            ],
            options={
                'verbose_name': 'Comisión del Desarrollador',
                'verbose_name_plural': 'Comisiones del Desarrollador',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_payment',), name='unique_commission_per_payment')],
            },
        ),
    ]
