# Generated by Django 5.2.3 on 2025-11-28 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('marketplace', '0006_order_estimated_delivery_date_and_more'),
        ('spa', '0012_alter_clientcredit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROCESSED', 'Procesado'), ('FAILED', 'Falló'), ('IGNORED', 'Ignorado')], default='PROCESSED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PARTIALLY_USED', 'Parcialmente Usado'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='AVAILABLE', max_length=20)),
                ('expires_at', models.DateField(blank=True, help_text='Fecha de expiración del crédito.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error'), ('TIMEOUT', 'Sin confirmación'), ('PAID_WITH_CREDIT', 'Pagado con Saldo a Favor')], default='PENDING', max_length=20)),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Anticipo de Cita'), ('FINAL', 'Pago Final de Cita'), ('PACKAGE', 'Compra de Paquete'), ('TIP', 'Propina'), ('VIP_SUBSCRIPTION', 'Membresía VIP'), ('ORDER', 'Orden de Marketplace')], default='ADVANCE', max_length=30)),
                ('transaction_id', models.CharField(blank=True, default='', help_text='Reference/transaction id from the payment gateway.', max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('customer_legal_id', models.CharField(blank=True, default='', help_text='Documento de identidad del pagador (para PSE, etc.)', max_length=50)),
                ('customer_legal_id_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('DNI', 'Documento Nacional de Identidad'), ('RG', 'Carteira de Identidade / Registro Geral'), ('OTHER', 'Otro')], default='', help_text='Tipo de documento del pagador', max_length=10)),
                ('tax_vat_in_cents', models.PositiveIntegerField(blank=True, help_text='IVA en centavos (incluido en amount, no se suma)', null=True)),
                ('tax_consumption_in_cents', models.PositiveIntegerField(blank=True, help_text='Impuesto al consumo en centavos (incluido en amount)', null=True)),
                ('payment_method_type', models.CharField(blank=True, choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('BANCOLOMBIA_TRANSFER', 'Botón Bancolombia'), ('BANCOLOMBIA_QR', 'QR Bancolombia'), ('DAVIPLATA', 'Daviplata'), ('BNPL', 'Buy Now Pay Later'), ('PCOL', 'Puntos Colombia')], default='', help_text='Método de pago utilizado en Wompi', max_length=30)),
                ('payment_method_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del método de pago (ej: financial_institution_code para PSE)')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='spa.appointment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.order')),
                ('used_credit', models.ForeignKey(blank=True, help_text='Crédito usado en este pago (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_payments', to='finances.clientcredit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], default='CREDIT', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_adjustments', to=settings.AUTH_USER_MODEL)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_related', to='finances.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientcredit',
            name='originating_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_credits', to='finances.payment'),
        ),
        migrations.AlterField(
            model_name='commissionledger',
            name='source_payment',
            field=models.ForeignKey(help_text='Pago original que generó la comisión.', on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='finances.payment'),
        ),
        migrations.CreateModel(
            name='PaymentCreditUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_usages', to='finances.clientcredit')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usages', to='finances.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_logs', to='finances.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
