# Generated by Django 5.2.3 on 2025-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_commissionledger_protect_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Reference/transaction id from the payment gateway.', max_length=100),
        ),
    ]
