# Generated by Django 5.2.3 on 2025-11-29 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_payment_transaction_id'),
        ('marketplace', '0009_productreview'),
        ('spa', '0015_add_analytics_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'status'], name='payment_time_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='payment_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_type'], name='payment_status_type_idx'),
        ),
    ]
