# Generated by Django 5.2.3 on 2025-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_paymenttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttoken',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
    ]
