# Generated by Django 5.2.3 on 2025-12-01

import hashlib
from django.conf import settings
from django.db import migrations, models
from cryptography.fernet import Fernet
import fernet_fields.fields


def backfill_payment_tokens(apps, schema_editor):
    PaymentToken = apps.get_model("finances", "PaymentToken")

    key = getattr(settings, "FERNET_KEYS", [None])[0]
    fernet = Fernet(key) if key else None

    for token in PaymentToken.objects.all():
        raw = token.token_id or ""
        fingerprint = hashlib.sha256(raw.encode()).hexdigest() if raw else ""
        masked = f"****{raw[-4:]}" if raw else ""

        updates = {
            "token_fingerprint": fingerprint or token.token_fingerprint,
            "token_id": masked,
        }

        if fernet and raw:
            try:
                updates["token_secret"] = fernet.encrypt(raw.encode()).decode()
            except Exception:
                pass

        PaymentToken.objects.filter(pk=token.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0008_alter_paymenttoken_id_alter_paymenttoken_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttoken",
            name="token_fingerprint",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="SHA256 del token para idempotencia/lookup sin exponer el valor real.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttoken",
            name="token_secret",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Token de pago cifrado en reposo (Fernet).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttoken",
            name="token_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
            ),
        ),
        migrations.RunPython(backfill_payment_tokens, reverse_code=migrations.RunPython.noop),
    ]
