# Generated by Django 5.2.3 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0009_secure_payment_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttoken",
            name="token_fingerprint",
            field=models.CharField(
                db_index=True,
                help_text="SHA256 del token para idempotencia/lookup sin exponer el valor real.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
