# Generated by Django 5.2.3 on 2025-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_paymenttoken_token_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('ERROR', 'Error'), ('TIMEOUT', 'Sin confirmación'), ('PAID_WITH_CREDIT', 'Pagado con Saldo a Favor'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
