# Generated by Django 5.2.3 on 2025-12-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_add_cancelled_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionledger',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='Método de pago usado (CARD, PSE, NEQUI, CASH, etc.).', max_length=30),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='payment_type',
            field=models.CharField(blank=True, default='', help_text='Tipo de pago que generó la comisión (copiado de source_payment).', max_length=30),
        ),
    ]
