# Generated by Django 5.2.3 on 2025-11-16 06:52

from django.db import migrations


def create_templates(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")
    templates = [
        (
            "APPOINTMENT_CANCELLED_AUTO",
            "EMAIL",
            "Tu cita fue cancelada automáticamente",
            (
                "Hola,\n\n"
                "Tu cita con ID {{ appointment_id }} programada para {{ start_time }} fue cancelada "
                "porque expiró el tiempo para realizar el anticipo.\n\n"
                "Si aún deseas el servicio, agenda una nueva cita en la app."
            ),
        ),
        (
            "APPOINTMENT_CANCELLED_AUTO",
            "SMS",
            "",
            "Tu cita {{ appointment_id }} fue cancelada por falta de anticipo. Agenda nuevamente desde la app.",
        ),
        (
            "APPOINTMENT_NO_SHOW_CREDIT",
            "EMAIL",
            "Se generó un crédito por tu cita",
            (
                "Hola,\n\n"
                "La cita {{ appointment_id }} fue marcada como No-Show según la política vigente. "
                "Se ha generado un crédito por {{ credit_amount }} en tu cuenta.\n\n"
                "Puedes usarlo en tu próxima reserva."
            ),
        ),
        (
            "APPOINTMENT_NO_SHOW_CREDIT",
            "SMS",
            "",
            "Cita {{ appointment_id }} marcada No-Show. Crédito generado: {{ credit_amount }}.",
        ),
        (
            "APPOINTMENT_NO_SHOW_PENALTY",
            "EMAIL",
            "Cita marcada como No-Show",
            (
                "Hola,\n\n"
                "La cita {{ appointment_id }} fue marcada como No-Show. "
                "No aplica reembolso según la política vigente.\n\n"
                "Si necesitas asistencia contáctanos."
            ),
        ),
        (
            "APPOINTMENT_NO_SHOW_PENALTY",
            "SMS",
            "",
            "Cita {{ appointment_id }} marcada No-Show. No aplica reembolso según política.",
        ),
    ]
    for event_code, channel, subject, body in templates:
        Template.objects.get_or_create(
            event_code=event_code,
            channel=channel,
            defaults={
                "subject_template": subject,
                "body_template": body,
                "is_active": True,
            },
        )


def delete_templates(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")
    Template.objects.filter(
        event_code__in=[
            "APPOINTMENT_CANCELLED_AUTO",
            "APPOINTMENT_NO_SHOW_CREDIT",
            "APPOINTMENT_NO_SHOW_PENALTY",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_templates, delete_templates),
    ]
