# Generated by Django 5.2.3 on 2025-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_cleanup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text='Notificaciones por WhatsApp'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationtemplate',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=False, editable=False, help_text='Push no disponible actualmente'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False, editable=False, help_text='SMS no disponible - usar WhatsApp'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('WHATSAPP', 'WhatsApp')], max_length=10),
        ),
    ]
