# Generated by Claude Code on 2025-11-26

from django.db import migrations


def create_whatsapp_templates(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")

    templates = [
        # ===== RECORDATORIOS DE CITAS =====
        (
            "APPOINTMENT_REMINDER_24H",
            "WHATSAPP",
            "",  # WhatsApp no usa subject
            """🗓️ *RECORDATORIO DE CITA*
Hola {{ user_name }},

Te recordamos que tienes una cita mañana:
📅 *Fecha:* {{ start_date }}
🕐 *Hora:* {{ start_time }}
💆 *Servicios:* {{ services }}

💰 *Total:* ${{ total }}

_Si no puedes asistir, cancela con al menos 24h de anticipación._

¡Te esperamos en StudioZens!"""
        ),
        (
            "APPOINTMENT_REMINDER_2H",
            "WHATSAPP",
            "",
            """⏰ *RECORDATORIO - CITA EN 2 HORAS*
Hola {{ user_name }},

Tu cita es en 2 horas:
🕐 {{ start_time }}
💆 {{ services }}

📍 Recuerda llegar 5 minutos antes.

¡Nos vemos pronto!"""
        ),

        # ===== CANCELACIONES DE CITAS =====
        (
            "APPOINTMENT_CANCELLED_AUTO",
            "WHATSAPP",
            "",
            """❌ *CITA CANCELADA AUTOMÁTICAMENTE*
Hola {{ user_name }},

Tu cita del {{ start_time }} fue cancelada porque no se realizó el anticipo a tiempo.

💡 *¿Aún quieres el servicio?*
Agenda nuevamente desde la app.

_Cualquier duda, contáctanos._"""
        ),

        # ===== NO-SHOW =====
        (
            "APPOINTMENT_NO_SHOW_CREDIT",
            "WHATSAPP",
            "",
            """💳 *CRÉDITO GENERADO*
Hola {{ user_name }},

Tu cita del {{ start_time }} fue marcada como No-Show.

✅ Se generó un crédito de *${{ credit_amount }}* en tu cuenta.

Puedes usarlo en tu próxima reserva.

_Gracias por tu comprensión._"""
        ),
        (
            "APPOINTMENT_NO_SHOW_PENALTY",
            "WHATSAPP",
            "",
            """⚠️ *CITA NO-SHOW*
Hola {{ user_name }},

Tu cita del {{ start_time }} fue marcada como No-Show.

Según nuestra política, no aplica reembolso.

_Si tuviste algún inconveniente, contáctanos._"""
        ),

        # ===== LISTA DE ESPERA =====
        (
            "APPOINTMENT_WAITLIST_AVAILABLE",
            "WHATSAPP",
            "",
            """🎉 *ESPACIO DISPONIBLE EN TU FECHA*
Hola {{ user_name }},

¡Buenas noticias! Se liberó un espacio para:
📅 {{ date }}
🕐 {{ time }}
💆 {{ service }}

💡 *Reserva ahora* desde la app antes que se agote.

_Este espacio puede llenarse rápido._"""
        ),

        # ===== VIP MEMBERSHIP =====
        (
            "VIP_RENEWAL_FAILED",
            "WHATSAPP",
            "",
            """⚠️ *ERROR EN RENOVACIÓN VIP*
Hola {{ user_name }},

No pudimos renovar tu membresía VIP porque:
{{ failure_reason }}

💡 *Para mantener tus beneficios:*
Actualiza tu método de pago en la app.

_Tu membresía vence el {{ expiry_date }}_"""
        ),
        (
            "VIP_MEMBERSHIP_EXPIRED",
            "WHATSAPP",
            "",
            """📢 *MEMBRESÍA VIP EXPIRADA*
Hola {{ user_name }},

Tu membresía VIP ha expirado.

💔 Perdiste acceso a:
• Descuentos exclusivos
• Prioridad en citas
• Vouchers mensuales

💡 *Renueva ahora* para recuperar tus beneficios.

_¡Te extrañamos!_"""
        ),
        (
            "VIP_LOYALTY_MILESTONE",
            "WHATSAPP",
            "",
            """🎊 *¡FELICITACIONES VIP!*
Hola {{ user_name }},

Alcanzaste {{ visits_count }} visitas como miembro VIP.

🎁 *Recompensa desbloqueada:*
{{ reward_description }}

_Gracias por tu lealtad._

¡Disfruta tu beneficio! 💜"""
        ),

        # ===== VOUCHERS =====
        (
            "VOUCHER_EXPIRING_SOON",
            "WHATSAPP",
            "",
            """⏰ *TU VOUCHER ESTÁ POR EXPIRAR*
Hola {{ user_name }},

Tienes un voucher de *${{ amount }}* que vence:
📅 {{ expiry_date }}

💡 *Úsalo antes que expire:*
{{ voucher_code }}

_No dejes pasar esta oportunidad._"""
        ),

        # ===== PAGOS =====
        (
            "PAYMENT_STATUS_APPROVED",
            "WHATSAPP",
            "",
            """✅ *PAGO APROBADO*
Hola {{ user_name }},

Tu pago fue procesado exitosamente:
💰 *Monto:* ${{ amount }}
🆔 *Referencia:* {{ reference }}
📋 *Concepto:* {{ concept }}

{{ extra_info }}

_Gracias por tu pago._"""
        ),
        (
            "PAYMENT_STATUS_DECLINED",
            "WHATSAPP",
            "",
            """❌ *PAGO RECHAZADO*
Hola {{ user_name }},

Tu pago fue rechazado:
💰 *Monto:* ${{ amount }}
🆔 *Referencia:* {{ reference }}
⚠️ *Motivo:* {{ decline_reason }}

💡 *Intenta de nuevo:*
• Verifica saldo disponible
• Confirma datos de tarjeta
• Contacta tu banco

_Si el problema persiste, contáctanos._"""
        ),
        (
            "PAYMENT_STATUS_ERROR",
            "WHATSAPP",
            "",
            """⚠️ *ERROR EN PAGO*
Hola {{ user_name }},

Ocurrió un error procesando tu pago:
💰 *Monto:* ${{ amount }}
🆔 *Referencia:* {{ reference }}

💡 *Intenta nuevamente* en unos minutos.

_Si el error persiste, contáctanos para asistencia._"""
        ),

        # ===== ÓRDENES MARKETPLACE =====
        (
            "ORDER_SHIPPED",
            "WHATSAPP",
            "",
            """🚚 *ORDEN ENVIADA*
Hola {{ user_name }},

Tu orden *#{{ order_id }}* ha sido enviada.

📦 *Guía de rastreo:* {{ tracking_number }}
📅 *Entrega estimada:* {{ estimated_delivery }}

💡 Rastrea tu pedido con el número de guía.

_¡Gracias por tu compra!_"""
        ),
        (
            "ORDER_DELIVERED",
            "WHATSAPP",
            "",
            """🎉 *ORDEN ENTREGADA*
Hola {{ user_name }},

Tu orden *#{{ order_id }}* fue entregada exitosamente.

✅ *Entregado:* {{ delivery_date }}

💡 *¿Todo llegó bien?*
Califícanos en la app.

_¡Esperamos verte pronto!_"""
        ),
        (
            "ORDER_CANCELLED",
            "WHATSAPP",
            "",
            """❌ *ORDEN CANCELADA*
Hola {{ user_name }},

Tu orden *#{{ order_id }}* fue cancelada.

📋 *Motivo:* {{ cancellation_reason }}
💰 *Reembolso:* {{ refund_info }}

_Si tienes dudas, contáctanos._"""
        ),
        (
            "ORDER_READY_FOR_PICKUP",
            "WHATSAPP",
            "",
            """🏪 *ORDEN LISTA PARA RECOGER*
Hola {{ user_name }},

Tu orden *#{{ order_id }}* está lista para recoger en tienda.

📍 *Dirección:* {{ store_address }}
🕐 *Horario:* {{ store_hours }}

💡 Lleva tu código: *{{ pickup_code }}*

_¡Te esperamos!_"""
        ),

        # ===== DEVOLUCIONES =====
        (
            "ORDER_RETURN_REQUESTED",
            "WHATSAPP",
            "",
            """🔄 *SOLICITUD DE DEVOLUCIÓN RECIBIDA*
Hola {{ user_name }},

Recibimos tu solicitud de devolución:
📦 *Orden:* #{{ order_id }}
📋 *Motivo:* {{ return_reason }}

⏳ *Estamos revisando tu caso.*
Te notificaremos la decisión en 24-48 horas.

_Gracias por tu paciencia._"""
        ),
        (
            "ORDER_RETURN_APPROVED",
            "WHATSAPP",
            "",
            """✅ *DEVOLUCIÓN APROBADA*
Hola {{ user_name }},

Tu devolución fue aprobada:
📦 *Orden:* #{{ order_id }}
💰 *Créditos abonados:* ${{ refund_amount }}

Puedes usar tus créditos en tu próxima compra.

_¡Esperamos verte pronto!_"""
        ),
        (
            "ORDER_CREDIT_ISSUED",
            "WHATSAPP",
            "",
            """💳 *CRÉDITOS ABONADOS*
Hola {{ user_name }},

Se abonaron *${{ credit_amount }}* a tu cuenta:
📋 *Concepto:* {{ reason }}
🆔 *Orden:* #{{ order_id }}

Usa tus créditos en tu próxima compra.

_¡Gracias por tu preferencia!_"""
        ),

        # ===== ALERTAS DE STOCK (Admin) =====
        (
            "STOCK_LOW_ALERT",
            "WHATSAPP",
            "",
            """⚠️ *ALERTA DE STOCK BAJO*
Los siguientes productos tienen pocas unidades:

{{ items_list }}

💡 *Acción requerida:*
Reabastecer inventario

_Notificación automática del sistema_"""
        ),

        # ===== USUARIO PERSONA NON GRATA (Admin) =====
        (
            "USER_FLAGGED_NON_GRATA",
            "WHATSAPP",
            "",
            """🚨 *ALERTA: USUARIO MARCADO COMO NON GRATA*
Usuario: {{ user_name }}
Email: {{ user_email }}
Teléfono: {{ user_phone }}

📋 *Motivo:* {{ flag_reason }}
🔒 *Acción:* {{ action_taken }}

💡 *Revisar perfil en admin:*
{{ admin_url }}

_Notificación de seguridad_"""
        ),

        # ===== BOT HANDOFF (Staff/Admin) =====
        (
            "BOT_HANDOFF_CREATED",
            "WHATSAPP",
            "",
            """🚨 *NUEVA SOLICITUD DE ATENCIÓN HUMANA*
{{ score_emoji }} Score: {{ client_score }}/100

👤 *Cliente:* {{ client_name }}
📞 *Tel:* {{ client_phone }}
{{ warning_text }}

💬 *Dijo:* "{{ escalation_message }}"

💡 *Responder desde admin:*
{{ admin_url }}

_Atender cuanto antes_"""
        ),
        (
            "BOT_HANDOFF_EXPIRED",
            "WHATSAPP",
            "",
            """⏰ *HANDOFF SIN ATENDER - EXPIRADO*
🚨 *ID:* {{ handoff_id }}
👤 *Cliente:* {{ client_name }}
📅 *Creado:* {{ created_at }}

⚠️ *No se atendió a tiempo*

💡 *Revisar caso:*
{{ admin_url }}

_Considerar recontactar al cliente_"""
        ),

        # ===== BOT SECURITY (Admin) =====
        (
            "BOT_SECURITY_ALERT",
            "WHATSAPP",
            "",
            """🔐 *ALERTA DE SEGURIDAD - BOT*
Tipo: {{ alert_type }}
Usuario: {{ user_identifier }}

📋 *Detalle:*
{{ alert_detail }}

⏰ {{ timestamp }}

💡 *Revisar logs en admin*

_Notificación automática del sistema_"""
        ),
        (
            "BOT_AUTO_BLOCK",
            "WHATSAPP",
            "",
            """🚫 *USUARIO AUTO-BLOQUEADO*
Usuario: {{ user_identifier }}

📋 *Motivo:*
{{ block_reason }}

🔒 *Acción tomada:* Bloqueo automático
⏰ {{ timestamp }}

💡 *Revisar caso en admin:*
{{ admin_url }}

_Bloqueo preventivo del sistema_"""
        ),
    ]

    for event_code, channel, subject, body in templates:
        Template.objects.get_or_create(
            event_code=event_code,
            channel=channel,
            defaults={
                "subject_template": subject,
                "body_template": body,
                "is_active": True,
            },
        )


def delete_whatsapp_templates(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")
    Template.objects.filter(channel="WHATSAPP").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_add_whatsapp_channel"),
    ]

    operations = [
        migrations.RunPython(create_whatsapp_templates, delete_whatsapp_templates),
    ]
