# Generated by Antigravity on 2025-11-26

from django.db import migrations


def create_bot_handoff_reply_template(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")

    # BOT_HANDOFF_REPLY
    Template.objects.get_or_create(
        event_code="BOT_HANDOFF_REPLY",
        channel="WHATSAPP",
        defaults={
            "subject_template": "",
            "body_template": """💬 *RESPUESTA DE SOPORTE*
Hola {{ recipient_name }},

{{ staff_name }} ha respondido a tu solicitud:

"{{ message }}"

💡 *Puedes responder a este mensaje.*""",
            "is_active": True,
        },
    )


def delete_bot_handoff_reply_template(apps, schema_editor):
    Template = apps.get_model("notifications", "NotificationTemplate")
    Template.objects.filter(event_code="BOT_HANDOFF_REPLY", channel="WHATSAPP").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_create_all_whatsapp_templates"),
    ]

    operations = [
        migrations.RunPython(create_bot_handoff_reply_template, delete_bot_handoff_reply_template),
    ]
